### PR TITLE
Support installing ClassicPress via composer

### PR DESCRIPTION
**Pull request by pierre-dargham**
Related to issue https://github.com/ClassicPress/ClassicPress/issues/37

This pull request provides the composer manifest file, at `src/composer.json`

- When a build is released on the (coming soon) github build repository, the `composer.json` will be at the root of the build.
- On packagist, we use the build repository to declare the composer package.

This addition, and the package declaration on https://packagist.org/users/ClassicPress/ will allow to :

- Install ClassicPress via composer in fresh projects
- Migrate from WordPress to ClassicPress via composer (if already a composer install)

### CODE REVIEW

**Comment by nylen** [comment]
> When a build is released on the (coming soon) github build repository

This already exists.

- Nightly builds: https://github.com/ClassyBot/ClassicPress-nightly (we'll make installs via Composer available here first)
- Official release builds: https://github.com/ClassicPress/ClassicPress-release (we'll put this on packagist with our next official release)

**Comment by nylen** [comment]
Thanks for the PR. I'd like for us to explore options around removing the `composer.json` file from the web root, but this will do for now.

**Comment by pierre-dargham** [comment]
Hi @nylen , thank you for merging the PR !

Now that we have https://github.com/ClassyBot/ClassicPress-nightly/blob/master/composer.json , could you declare the package on packagist.org, so we can check that everything works fine ?

> I'd like for us to explore options around removing the composer.json file from the web root

Agreed, we should come back to it soon.

**Comment by nylen** [comment]
> could you declare the package on packagist.org, so we can check that everything works fine?

@pierre-dargham when I go to do that, I see the following:

> The package name found for your repository is: classicpress/classicpress, press Submit to confirm.

If I am reading correctly, this will mean that the nightly builds will "take over" the `classicpress/classicpress` package name, which is not what we want.

We want to reserve that name for official releases and call this package `classicpress/classicpress-nightly` instead.  This will require a change to the build so that it updates the `composer.json` file with the desired package name (and I assume the correct version as well).

Does that sound right to you?

**Comment by pierre-dargham** [comment]
Hello @nylen,

Regarding your question :

**ClassicPress/ClassicPress-release** and **ClassyBot/ClassicPress-nightly** are the same software, but targeting different versions, so we shouldn't have two different composer packages names here, I think that it would be semantically wrong, and may be confusing.

By the way, you can change the source repository of a composer package at any time. So we could release the package `classicpress/classicpress` with **ClassyBot/ClassicPress-nightly** source for now, and when we are ready, set the source repository on **ClassicPress/ClassicPress-release**. If we do so, Packagist would just scan the source repository again, and provide package versions according to it (clearing all unmatched versions of the previous repo).

That said, if you want to avoid doing that, it's ok. Testing the composer install of the nightly builds can already be done pretty simply by modifying a project's composer.json. You just have to override the declared repository of the package, and set the `minimum-stability` to `dev`. See my example here (just tested it, and it works fine !)  : https://github.com/globalis-ms/wp-cubi/commit/fc45fac34424b3af43f8f98d0a6004e149bf6150

So I'm ok if we don't release the official composer package before next official release, because we already can do the tests. But I would avoid having a second classicpress-nightly composer package :)

**Comment by nylen** [comment]
Alright, that makes sense: we can dcument how to install the nightly build now.

Other than that, I'm reluctant to add a repository with versions that we know we're going to delete later, that also seems incorrect/confusing. I think we can wait for the beta release to publish this on composer.

**Comment by nylen** [comment]
I've opened https://github.com/ClassicPress/ClassicPress/issues/218 to track the documentation improvements.

**Pull request merged**
