### PR TITLE
Add support for PHPUnit 7 and 8

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
PHPUnit testing is in need to an update. Backporting of upstream changes is a good place to start.

## Motivation and context
This is a necessary stop for testing and declaring support for PHP 8.0 (and eventually 8.1)
This PR has relevance to an existing PR that enables tests on PHP 8.0:
https://github.com/ClassicPress/ClassicPress/pull/802

Currently testing supports PHPUnit 5 and 6, there are a few upstream tickets for reference on this and also a post in make/core.
https://core.trac.wordpress.org/ticket/38266
https://core.trac.wordpress.org/ticket/43218
https://core.trac.wordpress.org/ticket/46149
https://core.trac.wordpress.org/ticket/50902
https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/

This PR contains the following Backports:
42799, 44701, 44702, 44703, 44704, 44705, 44707, 44715, 44719, 44723, 44785, 44823, 44902, 44904, 44916, 44911, 44923, 44944, 44966, 45486, 46127, 46221, 46451, 46612, 46682, 46986, 47880, 48464, 48937, 48939, 48940, 48944, 48948, 48949, 48950, 48952, 48953, 48954, 48957, 48972, 48996, 48974, 49037, 49051, 49074, 49077, 49126, 49547, 49947, 50283, 50284, 51331, 51462, 51559, 51560, 51561, 51562, 51563, 51564, 51565, 51566, 51567, 51568, 51569, 51570, 51571, 51572, 51573, 51574, 51575, 51576, 51577, 51598, 51605, 51810, 51811, 51812, 51813, 51828

## How has this been tested?
After each step in back porting I have confirmed that PHPUnit 5 and 6 remain functional, and through each iteration PHPUnit 7 and then PHPUnit8 have been supported, tests have been updated and adapted.

Currently on the local install of PHP 7.4.23 PHPUnit 5,6,7 and 8 are all running 8272 tests with 52885 assertions, and all of these are passing.

Some points to note that arose during this PR workup.

1. The test file at `/tests/phpunit/tests/term/slashes.php` is a class extension of `WP_Ajax_UnitTestCase`. I can see no reason why this is the case because the tests are not contingent on Ajax, all other files in that folder are extensions of `WP_UnitTestCase`. It was necessary to change the `/tests/phpunit/tests/term/slashes.php` file to avoid testing hanging.
2. The `/tests/phpunit/tests/compat.php` tests contain a check that the `wp-includes/class-json.php` file produces a deprecation notice. However, due to differences in the `_deprecated_file` function in the `wp-includes/functions.php` file as compared to upstream it seems ClassicPress treats the deprecation as less severe, the test is therefore different.
3. During the backport of 51462, some array order changes caused tests to fail. I cannot explain why this happened but correcting the tests and subsequent backports have maintains passing unit tests.
4. Backporting of 48937 required some test type casting to ensure tests passed.

## Screenshots
N/A

## Types of changes
- New feature / Enhancement of existing feature

### CODE REVIEW

**Comment by bahiirwa** [comment]
Thanks for kickstarting this @mattyrob

**Comment by mattyrob** [comment]
Still some `grunt phpunit:multisite` issues left to fix.

**Comment by bahiirwa** [comment]
@mattyrob We have some conflicts

**Comment by mattyrob** [comment]
@bahiirwa - I suspect we will get more conflicts on merging #1105 so it might be worth waiting until we have that merged and looking again. Do you think #1105 is good to merge now based on your testing?

**Comment by bahiirwa** [comment]
#1105 can wait for this. It is a deprecation at the end of the year.

**Pull request merged**
