### PR TITLE
Coding Standards from Ticket 53635

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
This PR includes all relevant changes included in upstream ticket 53635:
https://core.trac.wordpress.org/ticket/53635
Of the 41 upstream commits, not all were not required.

There is still work to look at in:
https://core.trac.wordpress.org/ticket/53363 (and the tickets linked from here)
https://core.trac.wordpress.org/ticket/55656 (and some of the tickets linked from here)

## Motivation and context
Improve coding standards for readability and to aid move to PHP 8.1 compatibility.
It also commences work as described in the discussion on https://github.com/ClassicPress/ClassicPress-v1/issues/19

## How has this been tested?
Local PHPUnit and phpcs is passing and a quick manual localhost test looks good.

## Screenshots
N/A

## Types of changes
- Bug fix / Enhancement

### CODE REVIEW

**Review by bahiirwa — APPROVED** [review]
The changes came in neatly from backport. No errors on test with 8.1, 8.0 and 7.4

**Review by xxsimoxx — APPROVED** [review]
Tested for some days on a live site without errors.

**Comment by bahiirwa** [comment]
@mattyrob There is a new merge conflict in one file.

**Comment by mattyrob** [comment]
Closing as `wontfix` to prioritise efforts on ClassicPress v2

**Pull request closed without merging**
