### PR TITLE
Rearrange profile page so important fields are at top

### PR DESCRIPTION
**Pull request by ghost**
Moves the ‘Personal options’ section on the Profiles page further down. It can still be used and the options changed, but it isn’t the first thing you see.

## Description

This PR moves the whole table section in `user-edit.php` starting with
`<h2 class="user-profile-personal-options"><?php _e( 'Personal Options' ); ?></h2>`
below the ‘Account management’ table. I am not sure if this will cause any broader issues, but it works fine for me on a test site.

## Motivation and context

There is already a petition with c.50 votes to remove the admin colour scheme selector from the profile page completely. But it also has mixed comments, with a number of users saying it should remain.

I suspect the main problem is the prominence on the page it is given, because you always have to scroll past it to get to the more useful information.

## How has this been tested?

1. Copy in the revised version of the user-edit.php file
2. Visit your Profile page from the top menu see the new arrangement
3. Edit a user profile from the users section and also see the new arrangement
4. Add some plugins that extend this page (eg CC or WordFence) and check the new fields are correctly added below as usual

### Before

before

### After

new-profile

## Types of changes
- New feature

### CODE REVIEW

**Comment by nylen** [comment]
Why not hide the requested options using a bit of custom CSS and the CSS classes added in #448? This is what they were added for, and this way already exists (works today) and is much more flexible.

Anyway I agree that should be done as a separate change, this one is just for rearranging the profile fields and it's important to keep changes focused.

**Comment by nylen** [comment]
> For reasons of consistency: there are filters already on that page. Why use filters for some and CSS for others?

OK, not a problem, I was just wondering if there was a reason the existing method is not adequate.

Adding the new filter should still be done as a separate change, this PR is just for rearranging the fields and should be considered separately.

**Comment by simplycomputing** [comment]
If there is going to be an upcoming PR for filters to be added then I agree that will be a better overall solution. In that case this PR can be dropped.

**Comment by simplycomputing** [comment]
Closing this as it can now be addressed with this PR
https://github.com/ClassicPress/ClassicPress/pull/817

**Pull request closed without merging**
