### PR TITLE
Moved HTML text from Welcome Screen to About Page - about.php

### PR DESCRIPTION
**Pull request by GTMAN**
Move HTML text from dashboard welcome screen
https://github.com/ClassicPress/ClassicPress/issues/334#issue-399609888

## How has this been tested?
SandBox

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nylen** [comment]
@GTMAN in the future please do the following:

- Give your PRs a more informative title
- Include all code changes for the same issue in the same PR
- Include screenshots for visual changes

**Comment by GTMAN** [comment]
@nylen I didn't know how to combine different files in the same PR. I found an answer afterwards here.
[https://webapps.stackexchange.com/questions/95940/how-can-i-change-multiple-files-and-submit-them-in-one-pull-request-on-github](url) Not sure if I need to delete the fork in my repository after each PR is pushed to keep the files synced or not. I don't have a copy of the new child themes for example ...still learning github :)

**Comment by nylen** [comment]
> Not sure if I need to delete the fork in my repository after each PR is pushed to keep the files synced or not.

You can do this on your computer using git, and push the new branch(es) to GitHub. This is also the best way to make a pull request that changes multiple files.

Also check the Markdown syntax you're using to make links, it's not working.

**Comment by nylen** [comment]
Closing;  I've incorporated the commit in this PR into #337 so that we can merge both changes at the same time.

**Pull request closed without merging**
