### PR TITLE
WP-r52837: Media: Store attachment’s file size in metadata

### LINKED ISSUE #1026: Upstream: Media Metadata Improvements
Add these media metadata improvements from upstream

https://core.trac.wordpress.org/ticket/49412 - Store filesize media metadata
https://core.trac.wordpress.org/ticket/48164 - Store original URL when using media_sideload_image

Both of these are simple enhancements to store specific information around media metadata

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Media: Store attachment’s file size in metadata. 

Store the file size of all newly uploaded attachments, as part of the metadata stored in post meta. Storing file size means, developers will not have to resort to doing filesize function calls, that can be time consuming on assets on offloaded to services like Amazon’s S3. 

This change also introduces a new helper function called, wp_filesize. This is a wrapper around the filesize php function, that adds some helpful filters and ensures the return value is an integer.

Props Cybr, Spacedmonkey, SergeyBiryukov, johnwatkins0, swissspidy, desrosj, joemcgill, azaozz, antpb, adamsilverstein, uday17035. 
Fixes #1026 && #49412 - https://core.trac.wordpress.org/ticket/49412

## Motivation and context
Performance enhancement. PR also include WP-r52932 which relocates the new function to avoid errors.

## How has this been tested?
Upstream work and commit, unit testing included in patch

## Screenshots
N/A

## Types of changes
- Performance enhancement

### CODE REVIEW

**Comment by bahiirwa** [comment]
@mattyrob Do we want to add https://core.trac.wordpress.org/changeset/53380 to this as well?

**Comment by mattyrob** [comment]
@bahiirwa - It is already added:
https://github.com/ClassicPress/ClassicPress/pull/950/commits/7254316a12ddda20894401af04078e652897af01

**Comment by xxsimoxx** [comment]
LGTM.
Tested with custom snippet.

image

**Review by xxsimoxx — APPROVED** [review]
Looks good.
Tested with custom snippet.

image

**Pull request merged**
