### PR TITLE
Add a new default theme

### PR DESCRIPTION
**Pull request by KTS915**
This PR is the result of the discussion at https://classicpress.zulipchat.com/#narrow/stream/399228-plugins/topic/Migration.20Plugin/near/425782406

## Description
This PR adds a new default theme for ClassicPress, based on the theme now in use on the ClassicPress website at https://www.classicpress.net. The ClassicPress Theme is designed to be used in three ways:
- as is, with customizations made using the Additional CSS box in the customizer and/or via plugins;
- as a starter theme, where you customize any of the code as you wish, provided that you also rename the theme and the directory in which it resides so that it does not get accidentally overwritten; or
- as a parent theme, which you customize by creating a child theme.

Please note that using the theme as-is or as a parent theme will mean that the theme may be updated from time to time alongside a ClassicPress update. This will not happen if you use it as a starter theme and re-name it as indicated above.

### Special Features
The ClassicPress Theme comes with two accessible menus. The top one is for the main navigation. It automatically becomes a mobile menu with a search box on narrow screens. There is also a menu for use in the footer, if desired.

The footer also contains a series of static links to various locations on social media. Feel free to edit them or to override them in a child theme, according to the customization method you have chosen above.

The theme enables widgets to be added to a right sidebar, while specifying one sidebar for posts (the Blog Sidebar) and another for pages (the Main Sidebar).

The ClassicPress Theme also comes with a ready-made template for Frequently Asked Questions. To make use of this, create a custom post type for FAQs, register the post type as 'faq', and specify a URL for its archive (e.g. 'has_archive' => 'faqs' ). The theme will then display your FAQs using accessible disclosure widgets. Just remember to create a Custom Link to the FAQs in your menu!

## Motivation and context
- Provides users, especially those migrating from WordPress, with a lean, accessible theme that they can be sure will work on ClassicPress
- Better branding for ClassicPress. Currently we ship WP themes with a child CP theme, which simply advertises WP and makes us look overly dependent on it
- Shipping as default themes that are already child themes makes it impossible to use them as starter themes or to create new child themes. This theme can be used for both such purposes.

## How has this been tested?
On my localhost test site

## Screenshots
See the ClassicPress website at https://www.classicpress.net, but note that the `front-page.php` template used there is not included with this theme because that template is hard-coded.

## Types of changes
- New feature, not a breaking change

### CODE REVIEW

**Review by mattyrob — APPROVED** [review]

**Comment by xxsimoxx** [comment]
I see that ClassicPress logo is hardcoded.
I'd like the Site Identity -> Logo to be used.

Agree removing TwentyFifteen and TwentySixteen.

**Comment by xxsimoxx** [comment]
Fixed unit tests, `.gitignore` and text-domain.
@KTS915 please check if you are happy with those changes.

**Review by xxsimoxx — APPROVED** [review]
Works great!

**Comment by KTS915** [comment]
@xxsimoxx Those changes look great! I have now updated all the relevant files to use the new text domain, which I agree is the correct one.

**Comment by KTS915** [comment]
Great work, @xxsimoxx !

**Comment by xxsimoxx** [comment]
The only code that is not passing cpcs is `custom_sendfox_form_shortcode()` function in `functions.php`.
Wondering if it's useful to have a https://sendfox.com/ form shortcode. Seems to be hard-linked to a ClassicPress subscription.

**Comment by KTS915** [comment]
@xxsimoxx You're right, that shortcode definitely shouldn't be there. Just made a commit to remove it.

**Review by xxsimoxx — APPROVED** [review]

**Pull request merged**
