### PR TITLE
Optimized all images with ImgBot

### PR DESCRIPTION
**Pull request by Remzi1993**
Optimized all images with ImgBot, see: https://imgbot.net and https://github.com/marketplace/imgbot
It's a GitHub App you could install, after installation you could select all or some of your repos to start optimizing images.

### CODE REVIEW

**Comment by nylen** [comment]
We already have an image optimization process as part of the build, it doesn't cover every image in the repo but this is probably why the Travis CI build is failing.  Once this is fixed I'll be happy to merge this PR.

**Comment by Remzi1993** [comment]
I didn't know that. Thanks for the info 👍

**Comment by bahiirwa** [comment]
@nylen Could you please give pointers of how we can fix this?

**Comment by nylen** [comment]
Sure, the first step is to look at the Travis CI build log and see what it is complaining about. Click the red X for the failing build, then click Details, then click through to the failing job.

In this case there are three files that our existing optimization process would try to "re-optimize".  It's not ideal for a build process to have steps that modify the files in the repository itself, but we do have several of these (more details at #123).

Whenever a PR interacts with these build steps, then we need to run `grunt precommit` and commit the results. This avoids problems (unexpected file changes that are not accounted for) when it's time to do a release.

So, to fix this, run `grunt precommit` (or just back out the changes to the three files indicated in the build log) and I think this should be good to go.

**Comment by Remzi1993** [comment]
@nylen  Oeps, I use a GitHub App which force pushes my repo to stay up to date with the upstream repo. You could optimize the images with this if you still want to do this: https://github.com/marketplace/imgbot (it's free)

**Comment by nylen** [comment]
@Remzi1993 I would not recommend using this app, as it's going to make it much harder to collaborate on a PR with others (and to finish a PR that was in progress).

**Comment by Remzi1993** [comment]
@nylen Which App? ImgBot or Pull? I can do this PR again. I only need to change my forks repo default branch and set it up properly. ImgBot does PR's to the default branch.

**Comment by nylen** [comment]
the Pull app looks like it did something undesired here.

**Comment by Remzi1993** [comment]
@nylen It's fixed, I mean the Pull App, this happend because ImgBot does PR's to the default branch, which is undesired if you have a forked repo, see issue: https://github.com/dabutvin/ImgBot/issues/155

If I do changes I do tend to create a fix or feature branch to keep my changes separate.

**Pull request closed without merging**
