### PR TITLE
Replace media library grid view

### PR DESCRIPTION
**Pull request by KTS915**
## Motivation and context

The purpose of this PR is to replace the current media library grid view, which relies heavily on `jQuery` and `backbone.js`, with one built on PHP. There are several reasons for doing this:

1. Using much less JavaScript, and only for progressive enhancement, means that pages load faster and are "ready to go" as soon as they appear.
2. The JavaScript used is vanilla only; it doesn't use `backbone.js` or `jQuery` at all, and so helps advance the objective of phasing both out of ClassicPress.
3. The code is easy to understand and maintain, whereas the current JavaScript mess is something virtually no-one understands (including at WP). If we leave the code as it currently is and something changes or breaks, we will be struggling to fix it.
4. The new code has plenty of hooks that make the page customizable by developers; the current code has almost none.
5. The current code is out of date and does not follow best practices. The new code is much more accessible, including using the native HTML5 `dialog`  element for the modal.
6. The current layout involves some crazy CSS. This PR replaces that with CSS Grid.
7. The uploading is performed using the modern FilePond library which, unlike the current PlUpload library, is platform agnostic and not tied to TinyMCE, and so makes it easier for us to move away from TinyMCE as the default editor if we choose to do so.
8. FilePond is much easier to hook into and customize than PlUpload.

## Description
The new media grid looks and works in a very similar fashion to the current one, except that infinite scrolling has been replaced with pagination and a `Screen Options` setting to choose how many items should be shown per page.

Screenshot at 2024-09-22 08-52-09

Screenshot at 2024-09-22 09-00-09

## How has this been tested?
I have tested this on my localhost test site and also had reviewers comment on an experimental plugin. Thanks particularly to @mattyrob and @xxsimoxx !

I have made several optimizations since then. With an object cache in place, the experimental plugin made the same number of database queries (9) on my test site as the current media grid, but with a faster load time and much less JS. The code in this PR has reduced that to 5 queries.

## Type of change
- New feature

### CODE REVIEW

**Comment by mattyrob** [comment]
The failing test is due to differences in build caused by `rollup` in `Gruntfile.js`. If the idea here is for a static file at `src/wp-includes/js/media-grid.js` I can push an update to `rollup.config.cjs` and remove the unused build source files.

**Comment by KTS915** [comment]
Yes, that is the idea. This PR avoids using at least two large JS files that are currently used (though those files continue to be used elsewhere in CP at the moment).

I presume a new minified version of this new file will then also be created.

Thanks!

**Comment by mattyrob** [comment]
> I presume a new minified version of this new file will then also be created.

Yes, a minified version of the new file is created in the build process.

**Comment by KTS915** [comment]
Latest commit should resolve the issue @xxsimoxx identified.

**Review by xxsimoxx — APPROVED** [review]
Great! Now works very well!

**Pull request merged**
