### PR TITLE
 WP-r44272: WPDB: Check that `$wpdb->last_result` is countable before counting with it.

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
This is a backport of changeset 44272 that fixes PHP notices about countable data. It fixes errors are reports in ticket #641 

## Motivation and context
* Upstream patch and fix
* Fix for ticket #641 
* Fix for potential PHP notices

## How has this been tested?
Upstream testing of commit and patch includes unit tests built to test for the original issue and ensure the patch works.

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by bahiirwa** [comment]
Apart from Travis failing. It looks good.

**Comment by mattyrob** [comment]
@bahiirwa

Looking at the Travis reports the failures seem to be due to Copyright year not matching the current year.
There may also be something in the build and test configuration and multibyte and imagick don't seem to be available and 34 tests are skipped.

**Comment by timbocode** [comment]
I had similar build problems with Classic Commerce. The only way I found of fixing it was to drop back to composer 1.8.4. I just added the following line to`travis.yml`:

` - composer self-update 1.8.4`

May not be relevant here but thought I'd mention it.

https://github.com/ClassicPress-plugins/classic-commerce/pull/294

**Comment by nylen** [comment]
Build fixed in #651. I changed a WP `@ticket` annotation to `@see` with the full link, after that new build passes, this PR looks good for merge, thanks!

**Review by nylen — APPROVED** [review]

**Pull request merged**
