### PR TITLE
Fix fatal error uploading media on PHP8

### LINKED ISSUE #841: PHP8 error possible when uploading images
## Expected behavior
Errors should not occur when uploading images in PHP8
We can track this in the upstream ticket:
https://core.trac.wordpress.org/ticket/54385

## Current behavior
This issue here is the `wp_exif_frac2dec` function is supposed to return an integer or a float, but can occasionally return a string.
In PHP7 the string is evaluated to integer 0. In PHP8 an error is thrown.

## Possible solution
We can track upstream but a possible solution is to type cast the return from the `wp_exif_frac2dec` function to ensure an integer or float is returned in place of a string in all cases.

## Steps to reproduce (for bugs)
1. Image can be collected from upstream ticket
2. Ensure using PHP8 for testing
3. Test uploading the image
4.

## Context
Upstream reported bug and raised in Slack chat by Joy.

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Fixes #841 

As per the original Issue logged above, the is a possible PHP8 issue on uploading media. We have been tracking the upstream ticket and it seems it was patched and closed about 4 months ago.

## Motivation and context
This is an important ticket for PHP8 compatibility.

## How has this been tested?
PR includes unit tests, but will need manual confirmation.

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

**Review by xxsimoxx — APPROVED** [review]
Tested locally with some images and `sugarloaf-mountain.jpg` and solves the roblem.

**Comment by xxsimoxx** [comment]
Before:
image
`PHP Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /Users/simo/Sites/allMyPlugins/src/wp-admin/includes/image.php:466`
After:
(image is uploaded without errors)
image

**Comment by bahiirwa** [comment]
We have some merge conflicts on this @mattyrob 
Would like to review after that change.

**Comment by bahiirwa** [comment]
Adding on hold label until merge conflict is fixed.

**Review by bahiirwa — APPROVED** [review]
Works as expected. Make sure to use the image supplied for the test.

## Pre fix Screenshots
Screenshot 2022-08-29 at 09 47 39

Screenshot 2022-08-29 at 09 47 29

## Post Fix Screenshot
Screenshot 2022-08-29 at 09 48 56

**Review by bahiirwa — APPROVED** [review]

**Comment by mattyrob** [comment]
Community reviewed and screen shots demonstrate fix, good to merge.

**Pull request merged**
