### PR TITLE
Fix `Tests_Login::test_reset_password` for PHP 8

### PR DESCRIPTION
**Pull request by xxsimoxx**
`Tests_Login::test_reset_password` was failing under PHP 8

## Description
Don't know why. ~It can be an undocumented change in how PHP8 interprets the `m` modifier in regex.~ 
Just adding `\r?` before the `$` fix this.

## How has this been tested?
Local unit tests.

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by xxsimoxx** [comment]
Somewhere PHPMailer seems to be deleting `CR` when running in PHP 8.0.

**Comment by mattyrob** [comment]
@xxsimoxx - Great job tracking that down - does you patch work if we use `\n` instead of `\r`? I just think `\n` is more recognisable as the new line character.

**Comment by xxsimoxx** [comment]
`\n` is recognized as the end of the line and catched by the `$` in the regex. When the test fails is because `\r` is an extra char before the end of line so the regex don't match.

**Review by mattyrob — APPROVED** [review]

**Comment by mattyrob** [comment]
Looking at `src/wp-includes/user.php` the line endings are hard coded as `\r\n` so it seems the test does need updating to this.

While we are looking at this we can also conisder:
- updating `assertEquals` to `assertSame`
- adding a more up to date chack as well; `$this->assertRegExp( $regex, $mailer->get_sent()->body );`
- perhaps we can remove the `@runInSeparateProcess`, would need more testing but seems okay locally for me

**Comment by xxsimoxx** [comment]
The problem is that `$mailer->get_sent()->body` returns different line endings changing PHP version.

I've added this code in `tests/phpunit/tests/login.php` to see what happens:
```php
$x = $mailer->get_sent()->body;
$x = str_replace("\r", 'R', $x);
$x = str_replace("\n", 'N', $x);
var_dump($x);
```

Result in PHP 7.4:
`string(377) "Someone has requested a password reset for the following account:NNSite Name: Test BlogNNUsername: adminNNIf this was a mistake, ignore this email and nothing will happen.NNTo reset your password, visit the following address:NNhttp://example.org/wp-login.php?action=rp&key=0TCUylj8C5rCmB2V9h4m&login=adminNNThis password reset request originated from the IP address 127.0.0.1.N"`

Result in PHP 8.0:
`string(390) "Someone has requested a password reset for the following account:RNRNSite Name: Test BlogRNRNUsername: adminRNRNIf this was a mistake, ignore this email and nothing will happen.RNRNTo reset your password, visit the following address:RNRNhttp://example.org/wp-login.php?action=rp&key=yc0hGvw6ob9j7oZceuCT&login=adminRNRNThis password reset request originated from the IP address 127.0.0.1.RN"`

As you can see the hardcoded CRLF is preserved in PHP 8.0.

**Comment by xxsimoxx** [comment]
`$this->assertRegExp( $regex, $mailer->get_sent()->body );` throws a warning about `assertRegExp` being deprecated, so will move to `assertMatchesRegularExpression`.

Removing `@runInSeparateProcess` seems OK, and faster. 

Tests are passing locally and on GitHub.

**Comment by mattyrob** [comment]
Looks great to me, I'm going to push a change to the GH Actions to fully enable testing on PHP8 and let the checks run, if all if good I'll merge shortly.

**Pull request merged**
