### PR TITLE
Change the Configuration notices wording

### PR DESCRIPTION
**Pull request by bahiirwa**
Issue shared by @invisnet via Slack https://classicpress.slack.com/archives/CCCF22HG8/p1565050415029700

Help: just finished resolving a support request that boiled down to `/* That's all, stop editing! Happy blogging. */`

The code comment above can be confusing so this PR is aimed to give direction to the user on where to place their Config settings in the `wp-config.php` file.

## Description

Change the text 

> That's all, stop editing! Happy blogging.

 to 

> END custom settings. Any edit below this line may lead to unwanted errors.

## Motivation and context
It's an enhancement. It makes it easier for users with English as a 2nd language to receive a better notice to avoid breaking their config file.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mte90** [comment]
This can break things also require to change the consistency of the language in comment.
The reason of that is that the comment is friendly and also understable from non-techie people. Also is used by other plugin as sentence because is a common sentence in WordPress now.

Also break compatibilities with plugin like buddypress as written here https://wpdirectory.net/search/01DHKA6R0DHEA6ESXGPHW06BJP Because that wording is used to read and parse the wp-config file.

My suggestion is for the future to start a petition or an issue instead of a pull request so we can discuss it instead invest time on reviewing something that is not our priority and there is no interest on doing it.

**Comment by nylen** [comment]
There has been extensive discussion about this change in Slack, in particular @invisnet brought up an issue he saw in practice where a non-English-speaking IT professional was confused by the current wording.

We can do something like this instead:

```
/* START CONFIGURATION */
```

... (config settings here)

```
/* That's all, stop editing! */
/* END CONFIGURATION */
/* Adding or removing anything beyond this point may lead to unexpected errors. */
```

I looked at what Duplicator and BuddyPress are doing with these lines, and as long as we keep the `/* That's all, stop editing!` token as the first line, then they will still work.

Is this going to break anything else? Please take a look through https://wpdirectory.net/search/01DHKA6R0DHEA6ESXGPHW06BJP and advise if you see anything that will stop working.

**Comment by invisnet** [comment]
**Some history:**

The user was very technically proficient with good English, but not a _native_ English speaker. It took several hours of support, and ultimately access to the server, to work out that they'd done everything correctly, just in the wrong place:

> I never really got the point of the sentence: "That's all, stop editing!"

The root cause of the problem is that the phrasing isn't at all clear if English isn't your first language. The words are simple, but the meaning isn't.

**Fixing it:**

My first thought was to change the existing comment, but since it's used as a marker we can't do that; @nylen's solution of adding lines below the existing one looks like the right approach. I've had a quick look through the plugins that use it as a marker and I don't see any that would have a problem with some extra comments below the existing one.

I'm going to leave the exact wording of the new comments to others, but I do like @johnalarcon's suggestion for formatting:

```php
/* ---------- ADD CUSTOM CODE BELOW THIS LINE ------------------------------ */

/* ---------- ADD CUSTOM CODE ABOVE THIS LINE ------------------------------ */
```

**Comment by nylen** [comment]
If we are going to add a comment at the beginning then logically it makes sense to use `START` and `END`.

The best way to address problems with linguistic understanding is **repetition** - communicating the message several different ways.  Since we need to keep the existing comment in the same format, we can remove "happy blogging" as a bonus, add an `END` delimiter, and then explain a bit about **why** you shouldn't edit after the ending delimiter.

Let's not use the words "custom code" or "custom settings" - these are variations on the same standard settings that every site requires in order to function.

**Comment by bahiirwa** [comment]
> ```
> /* START CONFIGURATION */
> ```

Would this line go just above ``` // ** MySQL settings - You can get```?

**Comment by invisnet** [comment]
Yes, that should work - it doesn't look like anything uses that line as a marker: https://wpdirectory.net/search/01DHP0RR7RQVD64K72DWQRZZ21

**Comment by bahiirwa** [comment]
How do we deal with `src/wp-admin/includes/network.php` Since it has a translatable line of code with the same content?

**Comment by nylen** [comment]
Context:

https://github.com/ClassicPress/ClassicPress/blob/c63b679ffb754b204b43860857884b1a5f80b913/src/wp-admin/includes/network.php#L336-L345

https://github.com/ClassicPress/ClassicPress/blob/c63b679ffb754b204b43860857884b1a5f80b913/src/wp-admin/includes/network.php#L425-L436

This is providing instructions to users who are installing a multisite network, and the rule about adding any changes **above** the `Stop editing` line still applies, so all we need to do is remove the `Happy blogging` portion of these strings.

**Pull request closed without merging**
