### PR TITLE
Remove role="navigation" from `nav` elements

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
This is a backport from upstream ticket:
https://core.trac.wordpress.org/ticket/54054

## Motivation and context
This correct HTML to be syntactically correct for `nav` elements.

## How has this been tested?
Upstream tracking change but there may be a11y changes made prior to theis backport that should be considered before final merge.

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by steamboatid** [comment]
from SO [answer](https://stackoverflow.com/questions/14180785/html5-nav-element-vs-role-navigation) and [this](https://stackoverflow.com/questions/14180785/html5-nav-element-vs-role-navigation)

there are couple things we sould consider here.
CP, also WP, is not for **human only**, it's also for **Search Engine (SE)**.

It's true that human web browser is already modern enough to pick up the information and intended behaviour without the **role attribut**, but **NOT all of it**. some browsers is still left behind in the dust, while talking about html5.

the same condition also happened in the SE Crawler, most of them is not HTML5 compliance, yet.

so,
for the time being I think, it's more advisable to still add role attribute to all nav tags.

later,
once all of human browser and SE crawler already comply with HTML5, we can remove it all.
how about that ?

**Comment by viktorix** [comment]
This is a simple HTML change. Should we include this in 1.6.0?

**Comment by viktorix** [comment]
I'm trying to clean things up and close PRs that are no longer needed and move PRs to the v2.0 repo if necessary. I don't know what should be moved to v2.0, so I'm asking for feedback from others.

We will release 1.6.0 before releasing v2.0.

**Comment by KTS915** [comment]
> We will release 1.6.0 before releasing v2.0.

Will we? Why? That sounds like unnecessary work to me. Security updates I can understand, but not a new version.

**Comment by viktorix** [comment]
I don't remember if it was Slack or the forum, we discussed the final 1.6.0 version to include some last items. For example, removing the petitions widget, adding a v2.0 upgrade widget, and anything else we decide. v1.x is still technically LTS. So we shouldn't leave it broken. Removing the petitions widget alone would require a bump in the version number.

Everything on the 1.6.0 milestone list is on the chopping block. I'm just organizing everything to make it easier to manage, while closing unnecessary PRs.

**Comment by xxsimoxx** [comment]
We should also put deprecations in a minor before v2.

**Pull request closed without merging**
