### PR TITLE
WP-r43700: Customize: Increase the colour contrast of the line number…

### PR DESCRIPTION
**Pull request by MarcoZehe**
…s in CodeMirror.

WP:Props earnjam, abdullahramzan, audrasjb, Luminus.
Merges https://core.trac.wordpress.org/changeset/43574 to the 5.0 branch.
Fixes https://core.trac.wordpress.org/ticket/44763.

---

Merges https://core.trac.wordpress.org/changeset/43700 / WordPress/wordpress-develop@f959dfb850 to ClassicPress.

### CODE REVIEW

**Comment by MarcoZehe** [comment]
Whoops, this seems to be empty for some reason. But this must've been the case from the original WP commit, too.

**Comment by bahiirwa** [comment]
This could be the issue https://core.trac.wordpress.org/ticket/44763#comment:12

CP is based off the 4.9 branch

**Comment by MarcoZehe** [comment]
So... Which one should I merge instad to backport this?

**Comment by bahiirwa** [comment]
CP does not need it since it only affected the WP after 5.0 which have the block editor.

**Comment by MarcoZehe** [comment]
Gotcha. Closing this.

**Comment by nylen** [comment]
This has to do with the Additional CSS control in the Customizer, which was present in WP 4.9. It looks like we want https://core.trac.wordpress.org/changeset/43575 backported here (found by looking through the list of "Commits" at https://core.trac.wordpress.org/ticket/44763).

**Comment by MarcoZehe** [comment]
So, should this be reopened and another PR created with that changeset that gets merged first?

**Comment by MarcoZehe** [comment]
OK, this is now in PR #702 . I actually had to pull in 43574, because 43575 was not found due to probably some weird SVN to GitHub sync issue. But this applied cleanly and is the same change. Leaving this one closed, superceded by #702 .

**Pull request closed without merging**
