### PR TITLE
Remove Adobe Flash

### PR DESCRIPTION
**Pull request by KTS915**
This PR removes Adobe Flash entirely from not just CP core but from the whole CP bundle. In the words of [Can I Use](https://caniuse.com/?search=Flash):
```
The Adobe Flash player was used as a browser plug-in for interactive multimedia on web pages. It is no longer supported by Adobe as of December 31st, 2020. The latest versions of modern browsers no longer support Flash and the latest version of the Flash player will no longer load content on websites.
```

### CODE REVIEW

**Comment by mattyrob** [comment]
Searching in the code base a little there may well also be some code to update in `wp-admin/includes/media.php`, specifically in the `get_media_items()` and `media_upload_form()` functions.

**Comment by xxsimoxx** [comment]
How do we comply with SemVer with this?
I agree this is a bug fix, do you?
image

**Comment by KTS915** [comment]
This PR isn't about what type of files can be uploaded. (WP hasn't permitted SWF files to uploaded for a while, I believe.) It's about the uploader itself using Flash. Which isn't actually possible these days because no browser supports Flash. So the code that CP has that supports having Flash as a fallback for the uploader is redundant because it simply could never be used.

I suppose you could call this a bug fix. But it certainly isn't a breaking change because it couldn't be used anyway. So I don't think there's any issue with SemVer.

**Comment by xxsimoxx** [comment]
Thank you for explaining. Ok, don't think too that is an issue for SemVer.

**Review by xxsimoxx — APPROVED** [review]

**Pull request merged**
