### PR TITLE
Replaced WordPress logos with ClassicPress logos

### PR DESCRIPTION
**Pull request by frozzare**
Replaced logos in /wp-admin/images and /wp-includes/images, see #5 for more info.

### CODE REVIEW

**Comment by nylen** [comment]
Hi @frozzare, thanks for doing this.

The two WP `.svg` logos are square, but their replacements are not:

2018-08-31t11 27 08-05 00

Can you fix the aspect ratio on these two files, please?  Then this PR should be good to go as an initial step (the files still need to be renamed, but per https://github.com/ClassicPress/ClassicPress/issues/5#issuecomment-417005066 I see that will happen later).

**Comment by frozzare** [comment]
@nylen will try! not so good with svgs.

**Comment by nylen** [comment]
Wait, actually, it is GitHub's diff tool being misleading here, sorry.  I think everything is fine.  Both SVG files say this:

`viewBox="0 0 138.5 138.5"`

which is a square aspect ratio.

**Comment by frozzare** [comment]
Great :)

**Comment by nylen** [comment]
I pushed a commit to set the SVG file permissions from `755` back to `644`.  I'll merge this PR after the Travis build passes.

**Pull request merged**
