### PR TITLE
WP-r47181: Posts, Post Types recover orphaned content.

### PR DESCRIPTION
**Pull request by bahiirwa**
Single post with an unregistered post status should be displayed in `WP_Query::get_posts()`.

If the post status is not registered, assume it's not public, but still allow access to users with edit permissions (same as for a protected post status, e.g. `draft`), so that they could recover orphaned content.

- Add unit tests.

Follow-up to https://core.trac.wordpress.org/changeset/47178.

WP:Props roytanck, SergeyBiryukov.
Fixes https://core.trac.wordpress.org/ticket/48653.

Conflicts:
  src/wp-includes/class-wp-query.php
  tests/phpunit/tests/query/postStatus.php
----
Merges https://core.trac.wordpress.org/changeset/47181 / WordPress/wordpress-develop@5e8563eb6b to ClassicPress.

### CODE REVIEW

**Comment by nylen** [comment]
One issue is that this PR is missing https://core.trac.wordpress.org/changeset/47178 which is part of the same ticket.

Another issue is that I don't understand what is being changed and why. Do we have a real-world use case where this behavior impacts ClassicPress sites?

**Comment by bahiirwa** [comment]
> One issue is that this PR is missing https://core.trac.wordpress.org/changeset/47178 which is part of the same ticket.

Updated.

> Another issue is that I don't understand what is being changed and why. Do we have a real-world use case where this behavior impacts ClassicPress sites?

Custom post statuses are used by plugins in custom post types. These could adopted as user migrate from WP to CP.

**Ref:** 
WP Repo: https://wordpress.org/plugins/tags/post-status/, https://wordpress.org/plugins/extended-post-status/
Custom plugins: https://www.wpbeginner.com/wp-tutorials/how-to-add-custom-post-status-for-blog-posts-in-wordpress/

**Comment by nylen** [comment]
Ok, so this is a "could be an issue" rather than "definitely is an issue for us".

Looking at our [PR review criteria](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#review-criteria):

1. :x: **The change impacts existing ClassicPress users.** (Not that we know of.)
2. :question: **The change is not going to break backward compatibility.** (Presumably WP has done their homework here, but I don't understand this well enough to be sure.)
3. :heavy_check_mark: **The change has automated tests.** (Yes, although they are currently not passing.)
4. :x: **We understand the code change very well or can ask questions of someone who understands it very well.** (Doesn't seem like it.)

It would probably take me around 6 hours to understand and test this code in depth. I think at least right now that time is much better spent in other places.

**Comment by bahiirwa** [comment]
Maybe we should close this for now as it is not an issue per say.

**Comment by nylen** [comment]
I agree with closing this for now. If you want, just leave the branch in your repository and we can re-open later.

Also, I restarted Travis CI and it passed this time.

**Comment by bahiirwa** [comment]
Closing until needed

**Pull request closed without merging**
