### PR TITLE
Update license.txt

### PR DESCRIPTION
**Pull request by KTS915**

### CODE REVIEW

**Comment by nylen** [comment]
Looks like there are some automated tests that are checking this line in the license file, probably to make sure that it's updated for each new year. We'll want to update those here too.

**Comment by KTS915** [comment]
@nylen @senlin For the purposes of US law, the © symbol should be included.

**Comment by Mte90** [comment]
I am wondering if we have to change the text in ClassicPress and is contributors because ClassicPress in the license is not define what is.
If also WordPress that is a non-profit doesn't write that I think that is better to leave `by contributors`

**Comment by senlin** [comment]
@Mte90 I always assume that lawyers know better what they talk about than laymen :)

**Comment by Mte90** [comment]
Probably yes but I think that this important to explain that change and write somewhere because can be a discussion point for the future of the project.

**Comment by senlin** [comment]
🎉🎉🎉Many congrats @KTS915 on your first PR! 🎉🎉🎉

**Pull request merged**
