### PR TITLE
Multiple select support for wp_dropdown_categories

### PR DESCRIPTION
**Pull request by smileBeda**
## Description
Adds a new argument to the $args array for `wp_dropdown_categories`, allowing to pass either empty string or `multiple`. 

If left empty, the select defaults to a single select, if `multiple` is passed the Select will allow for multiple selection and pass an `[]` to the name attribute value as well.

See also https://forums.classicpress.net/t/update-wp-dropdown-categories-to-allow-for-multiple-selection/

## Motivation and context
The requirement to produce a Categories or else Custom taxonomy Dropdown with multiselect support has been around for years (google search will show what I mean).
I use to replace said function in my plugins with this (and other) amendments and thus I think it is time to have this tiny, but powerful change in core.

## How has this been tested?
This was tested on several installs of mine (I use to replace said function with a custom one). Also tested this particular commit on my local install
Example usage:
`wp_dropdown_categories( array('multiple' => 'multiple') );`

### Before
Screenshot 2021-09-10 at 11 06 25

### After
Screenshot 2021-09-10 at 11 06 37

NOTE:
This now also allows for Select2 MultiSelects, of course (the developer just needs to instantiate S2 on the select input produced...)

## Types of changes
- New Feature (backwards compatible and non-disturbing)

### CODE REVIEW

**Comment by nylen** [comment]
Needs testing (including automated tests) and revision (changing `multiple` to a boolean value) similar to #791 .

**Comment by TukuToi** [comment]
Pushed 2 commits that:
- Fix poorly styled @since version (remove CP- prefix)
- Transform new argument to boolean
- Add validation for new (and existing) boolean arguments
- Update logic to print `multiple` or nothing depending on new argument value passed to `wp_dropdown_categories`

Tested locally for functionality as well.
-

**Comment by smileBeda** [comment]
This shouldn't be closed.

**Comment by mattyrob** [comment]
I suspect this auto closed due to fork where PR originated being deleted.

**Comment by bahiirwa** [comment]
Unfortunately, the branch is closed. Needs re-opening.

**Comment by smileBeda** [comment]
As per latest decisions it seems CP will be re-forked, re-synced with WP, so I think the changes of this PR (and all others I committed in the past improving similar functions) can/should be discarded, since they add _new_ features not in WP and thus would just complicate the keeping-in-sync process.

**Pull request closed without merging**
