### PR TITLE
Updating financial contributors in README.md

### PR DESCRIPTION
**Pull request by viktorix**
## Description
Primarily, I had to add organizations to the financial contributors section since we got one donor that's an organization. I also fixed a few minor text and URL issues I did not notice before.

## Screenshots
image

### CODE REVIEW

**Review by bahiirwa — APPROVED** [review]
Looks good.

**Comment by KTS915** [comment]
Yay! 😀

**Comment by bahiirwa** [comment]
@viktorix Are these to be manually added everytime? I thought the script does that in automation.

**Comment by viktorix** [comment]
@bahiirwa it's somewhat automatic. The individual and organization contributors are automatic now. The sponsors will need to be manual because we need a logo and a domain to link to. The automatic integration generates SVG, which means we can't link individual icons. So sponsors need to be manual. I doubt we will have many, so we shouldn't be doing this often. I did push updates now.

**Comment by viktorix** [comment]
image

**Comment by bahiirwa** [comment]
Update looks good as well.

**Comment by viktorix** [comment]
@bahiirwa does this still need to be on hold?

**Comment by bahiirwa** [comment]
Looks good for merge.

**Comment by en1985** [comment]
Just a heads up, I don't know if I did the edit on GitHub properly so maybe someone else can handle this. The readme for corporate sponsors if you click the link "become a sponsor" it goes to babel's sponsorship page.

**Comment by bahiirwa** [comment]
> Just a heads up, I don't know if I did the edit on GitHub properly so maybe someone else can handle this. The readme for corporate sponsors if you click the link "become a sponsor" it goes to babel's sponsorship page.

Thanks for raising this. The link in the develop branch is still working as expected. I have looked at the link in the readme and also manually clicked it to test. Maybe the issue you have is local.

**Comment by viktorix** [comment]
@en1985 thanks for reporting. It is an issue. I remember changing it, but I guess I never saved changes before creating a PR. I created a new PR #1061 to fix it (@bahiirwa).

**Comment by bahiirwa** [comment]
I was only checking the sponsor image link. Thanks for catching this.

**Pull request merged**
