### PR TITLE
Add changelogs info #449

### PR DESCRIPTION
**Pull request by bahiirwa**
Add changelog notes in about.php

## Description
PR for https://github.com/ClassicPress/ClassicPress/issues/449 

## Motivation and context
Add links and information to explain CP changes and new features in new releases.

## How has this been tested?
This is markup and has non-breaking changes. Code has been tested with Code standards and visually.

## Screenshots (if appropriate):
Screen Shot 2019-07-19 at 12 16 58

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mte90** [comment]
We didn't defined where show that, the original ticket #449 say in the dashboard and this will be shown on the bottom in the about page.
I think that is better to put on top that is more easy to find.

**Comment by bahiirwa** [comment]
Honestly, I think changelog deserves its own tab as it can grow. That would be a better option. But James might have a reason as there will be a different approach after 1.1.0

**Comment by Mte90** [comment]
there is #422 for that as we said at the last meeting

**Comment by nylen** [comment]
Changelogs are in order from newest to oldest so the ClassicPress changes should go above the WordPress changes.

Adding a new tab would be something to consider for after we have the full changelogs in the dashboard, but not for now. We'd probably need to change the content in the About tab in order to make this work well, and in general it's not a good idea to make large changes like that close to a release.

**Comment by bahiirwa** [comment]
> Changelogs are in order from newest to oldest so the ClassicPress changes should go above the WordPress changes.

Change made to this effect.

> Adding a new tab would be something to consider for after we have the full changelogs in the dashboard, but not for now. We'd probably need to change the content in the About tab in order to make this work well, and in general it's not a good idea to make large changes like that close to a release.

Noted

**Pull request merged**
