### PR TITLE
Avoid the use of globals in get_the_content() and related functions

### LINKED ISSUE #1082: Posts: Avoid the use of globals in get_the_content() and related functions
I'm opening this issue so it serves as a base for a future PR that I will submit after #1051 gets merged, but since I already tested this and it fixes the problem, I'm leaving it here so it doesn't get lost.

This is a fix for [WP 42814](https://core.trac.wordpress.org/ticket/42814).

The changesets that fix this are [#44941](https://core.trac.wordpress.org/changeset/44941) and [#48114](https://core.trac.wordpress.org/changeset/48114).

### PR DESCRIPTION
**Pull request by alvarofranz**
Fixes #1082 - See details there.

### CODE REVIEW

**Comment by 3v-afranz** [comment]
# How to test this PR

In your theme, replace the contents of your _single.php_ file with:

```
<?php

get_header();
the_content(); // We're out of the loop
get_footer();
```

And you'll get a warning on the front end with PHP 7.2+

`Warning: count(): Parameter must be an array or an object that implements Countable in C:\laragon\www\classicpress\ClassicPress\src\wp-includes\post-template.php on line 284`

With this PR, that is fixed.

**Comment by alvarofranz** [comment]
# How to test this PR

In your theme, replace the contents of your _single.php_ file with:

```
<?php

get_header();
the_content(); // We're out of the loop
get_footer();
```

And you'll get a warning on the front end with PHP 7.2+

`Warning: count(): Parameter must be an array or an object that implements Countable in C:\laragon\www\classicpress\ClassicPress\src\wp-includes\post-template.php on line 284`

With this PR, that is fixed.

**Comment by bahiirwa** [comment]
@alvarofranz We have merge conflicts here. Would you like to deal with them?

**Comment by alvarofranz** [comment]
HI @bahiirwa - Sorry, was doing other things. It seems you already fixed the merge conflict, which was just one extra line?

**Comment by bahiirwa** [comment]
Thanks for making time for this. #815 will help with this soon. This should be in the queue after that merge.

**Comment by mattyrob** [comment]
@alvarofranz - I've had another go at creating this PR and have it passing unit tests locally. Are you happy for me to close this PR and open a new one?

**Comment by wp-cms** [comment]
Very happy :)

**Comment by mattyrob** [comment]
Closing in favour of #1123

**Pull request closed without merging**
