### PR TITLE
Modify the current color picker to remove jQuery UI dependencies

### PR DESCRIPTION
**Pull request by KTS915**
## Description
This PR is the latest in my quest to eradicate the usage of jQuery UI in CP core. It replaces PR #1293, which I have now closed.

## Motivation and context
This PR removes jQuery UI as a dependency for the color picker Iris. It does so by bundling the unminified version of Iris and then modifying that so that both the jQuery UI components `draggable` and `slider` are replaced by native HTML5 drag-and-drop and `<input text="range">` respectively.

These replacements make the code far leaner and faster.

## How has this been tested?
On my localhost install, using both Firefox and Chrome. I discovered a bug in Firefox when using vertical sliders but have allowed for (and noted) that in my code, so that these changes should work in every browser supported by CP.

## Screenshot After

Screenshot at 2024-01-13 15-04-03

Note that the slider will look different in each browser because that is handled by the browser itself.

## Types of changes
New feature: this is not a breaking change since the whole point has been to make it work with current themes.

### CODE REVIEW

**Comment by mattyrob** [comment]
If helpful, and as Iris is an external library, we can exclude it from the code standards checks. We are including it rather than authoring it ourselves so that is reasonable.

**Comment by KTS915** [comment]
That would be helpful, thanks! There's a couple of function expressions that would be hard to re-write as declarations without unproductive refactoring.

After further testing I see there is still one thing I need to fix: getting the slider to start in the right position after a page refresh. (The color itself is right, but the slider always starts at 50%, which isn't.)

**Comment by KTS915** [comment]
The slider now starts in the right position after a page refresh, so this is good to go for proper testing!

**Review by xxsimoxx — APPROVED** [review]
Looks good:

image

**Comment by mattyrob** [comment]
I have a plugin that uses the color picker to allow the user to style an element for display on their site.

In testing I have noticed two things:
1/ In Firefox and Safari, when dragging the color selector circle there is a visual artefact the follows it around and that seems to migrate to the starting position when the mouse is released.
2/ The vertical slider doesn't move in Safari, although the color hex value does seem to update.

**Comment by KTS915** [comment]
Both the vertical slider issue in Safari and the ghost image artefact in the color picker should now be resolved.

**Comment by KTS915** [comment]
I've just been testing on a touch device and found that the new sliders work perfectly on touch. The old ones did not work with touch at all.

**Comment by KTS915** [comment]
@mattyrob, @xxsimoxx  There's one remaining jQuery UI dependency here: it's the jQuery UI core file. In fact, however, the color picker just needs the `widget` part, which used to be in its own discrete module anyway.

It's too complex to think of re-writing, so it would seem sensible just to split it back out and have it as a separate file once again. That might be true of other parts of the core file too; I haven't looked into all of that yet. But this one raises an issue which — apart from maybe the `position` one — they don't.

Because it used to be in its own file, the jQuery UI `widget` still has its own listing in `wp-includes/script-loader.php` in case of backward compatibility. It doesn't actually refer to a file, though; it just lists a dependency on jQuery UI core. 
But the file nevertheless exists in core, again in case of backward compatibility!

So here's my question. If you agree that splitting out the `widget` part from the core file makes sense, what should I call the new file? Can I just use the current listing, but actually provide a proper file path and remove the dependency on jQuery UI core? That would be the simplest thing. Or is that a breaking change? If it's the latter, what should I call the new file?

**Comment by KTS915** [comment]
Another question, @mattyrob : If Iris is excluded from code standards checks, will the build process still make a minified file out of it? I hope so!

**Pull request merged**
