### PR TITLE
Add "Copy" button to "All Settings" screen 

### PR DESCRIPTION
**Pull request by xxsimoxx**
## Description
Add "Copy" button to "All Settings" screen (`wp-admin/options.php`) to copy the content of the option.
If the option is serialized a `var_dump` of the option will be copied.

image

## Motivation and context
While allowing the user to modify serialized options is risky, allowing them to copy their contents offers the possibility of extracting data from these options.

Without the ability to see serialized options this screen loses some of its usefulness.

## How has this been tested?
Local testing.

## Types of changes
- New feature

### CODE REVIEW

**Review by KTS915 — CHANGES_REQUESTED** [review]
Two things:

1. This seems to work when serialized data are copied, but I am also seeing a `var_dump` even when I try to copy a string, and the array shown does not seem to relate to the string at all.
2. The method used to copy the values is `navigator.clipboard.writeText`. This is the right choice, but it works only on `https` and `localhost`. Should we add a fallback for sites on http connections or are we satisfied that we shouldn't do that because of the potential security risk?

**Comment by xxsimoxx** [comment]
Can't reproduce (1). When I copy a string I paste the same string, not a `var_dump`.

About (2) don't think that http-only needs a fallback but I can add if needed, or just not show buttons if `wp_is_using_https()` is false.

**Comment by KTS915** [comment]
I have (1) working now.

On (2), I think it's the right idea not to show the Copy button if copying isn't possible, and I also agree that we shouldn't allow it on insecure sites. But wouldn't checking for `wp_is_using_https()` mean that copying on `localhost` would also be disabled?

Wouldn't it better to do the check like this: `if ( navigator.clipboard ) {`?

**Comment by xxsimoxx** [comment]
> Wouldn't it better to do the check like this: if ( navigator.clipboard ) {?

There is now a check that removes the buttons if not using HTTPS and not on localhost.

**Review by KTS915 — APPROVED** [review]
Works well!

**Comment by mattyrob** [comment]
In terms of the output of the serialized data, if we can accept the slight variation in the data returned I think we should try to use `print_r()` rather than `var_dump()`, although `var_export()` is another option perhaps. But both `var_*()` functions provide a little more details but print_r is designed to be more human-readable.

So rather than:
```
ob_start();
$unserialized_value = unserialize( $option->option_value );
var_dump( $unserialized_value );
$clipboard_text     = ob_get_contents();
ob_end_clean();
```

How about this (it avoids the need to use an output buffer too):
```
$unserialized_value = unserialize( $option->option_value );
$clipboard_text     = print_r( $unserialized_value, true );
```

**Comment by xxsimoxx** [comment]
At the beginning I used `print_r`. The output is more readable, but it misses types, nulls...

Really I don't have a preference, so let me know what's the perfered output.

Example with `print_r`:
```
    [zh_CN] => Array
        (
            [language] => zh_CN
            [version] => 1.0.0
            [package] => https://api-v1.classicpress.net/translations/core/2.0.0/zh_CN.zip
            [english_name] => Chinese Simplified
            [native_name] => 简体中文
            [iso] => Array
                (
                    [0] => zh-cn
                    [1] => 
                    [2] => 
                )

            [updated] => 2024-09-22 10:06:07
            [strings] => Array
                (
                    [continue] => Continue
                )

        )
```

Example with `var_dump`:
```
  ["zh_CN"]=>
  array(8) {
    ["language"]=>
    string(5) "zh_CN"
    ["version"]=>
    string(5) "1.0.0"
    ["package"]=>
    string(65) "https://api-v1.classicpress.net/translations/core/2.0.0/zh_CN.zip"
    ["english_name"]=>
    string(18) "Chinese Simplified"
    ["native_name"]=>
    string(12) "简体中文"
    ["iso"]=>
    array(3) {
      [0]=>
      string(5) "zh-cn"
      [1]=>
      NULL
      [2]=>
      NULL
    }
    ["updated"]=>
    string(19) "2024-09-22 10:06:07"
    ["strings"]=>
    array(1) {
      ["continue"]=>
      string(8) "Continue"
    }
  }
```

**Pull request merged**
