### PR TITLE
Move require of wp-settings.php from wp-config to wp-load, redux. 

### PR DESCRIPTION
**Pull request by mikeschinkel**
This is a PR to isolate to core aspects of https://github.com/ClassicPress/ClassicPress/pull/238

### CODE REVIEW

**Comment by mikeschinkel** [comment]
@ginsterbusch Please provide at least one example of plugins in the wild that this change would break as you stated in https://github.com/ClassicPress/ClassicPress/pull/238#issuecomment-439609412 so we can modify this PR if need be.

**Comment by ginsterbusch** [comment]
I think its Ajax Search Pro, but I cannot pinpoint it right now. Alas, I'm testing with my own custom system (which is NOT publicly available, as its custom work for a client) if the moving might lead to some different issue.

Might be false alarm though.

**Comment by nylen** [comment]
Some discussion in Slack also, that I will summarize when I'm at the computer.

From what I understood it has to do with plugins loading WordPress by requiring wp-config.php directly.

**Comment by nylen** [comment]
From @ginsterbusch in Slack:

> Eg. A lot of plugins implement their own AJAX or fetch API "endpoint", by bootstrapping WP via wp-config.php. Also to properly run a working WP environment one cannot leave out wp-config, else one wouldn't have access to the config data. But also only loading wp-load + wp-config AFTERWARDS fails, because of the already included WP env (in wp-config). TL;DR: Quite a few plugins, who require the current WP env., have to include wp-config, because else hell breaks loose.

---

I also did a scan of the plugin directory.  There is still a long tail of plugins that require `wp-config.php` (1,281 plugins from the WP plugin directory, definitely some false positives but also some valid results).  Here are the most common ones, with reported active install numbers of 50,000 or more:

```
Matches  Plugin                 Active installs
=======  ======                 ===============
      1  gotmls                        200,000+
      1  formidable                    200,000+
      3  accelerated-mobile-pages      100,000+
      1  post-views-counter             80,000+
      6  ckeditor-for-wordpress         50,000+
      3  xcloner-backup-and-restore     50,000+
      3  wp-mail-logging                50,000+
```

I don't have time to test right now, but I suspect that all of these plugins that are not false positives are loading WordPress by requiring `wp-config.php`.

This PR will break this use case, as dubious as it is, so I don't think we can merge it as-is.

---

We can do better than this for another reason, though:  we can support the original goal of this change (make the `wp-config.php` file loadable and parseable) for existing installs also, not only new installs.

From https://github.com/ClassicPress/ClassicPress/issues/197#issuecomment-434560781:

> add an environment variable like `CLASSICPRESS_PARSE_CONFIG_ONLY` that causes `/wp-settings.php` to exit immediately, instead of continuing with the load process.

This could also be a `define` or a global variable rather than an environment variable, I don't have a preference there.

Given that people still load WordPress by requiring `wp-config.php` I think it's the way we need to go here.

---

There is also one more "loose end" here from @ginsterbusch in Slack:

> AFAIR one cannot disable theme inclusion with wp-load, while with wp-config one is able to define a constant that tells WP it already ran the theme / template engine.
>
> its a stack exchange thread that asks about WP bootstrap best practices with 200+ up rating for the answer, referenced a lot on the net.

I am not sure that we need to investigate too much more, though.  I think it is better (for multiple reasons) to do this change in a way that cannot possibly break anything - i.e. no behavior change whatsoever unless a new flag is set.

**Comment by mikeschinkel** [comment]
@nylen @ginsterbusch Sad to think that people call `wp-config.php` instead of `wp-load.php`.  It never occurred to me they load wp-config.php when wp-load.php is available explicitly for that purpose. But now that I am actively contributing to open source I guess I have to think more about how people are likely not to follow best practices.

I have updated to the PR per @nylen's request and used `LOAD_CONFIG_ONLY` as @nylen  proposed in Slack:
load_config_only

Given the suggestion that we could possible get WordPress and CalmPress to adopt this I also dropped the `CP_` prefix from `CORE_PATH` and `CONTENT_PATH`; hope that was okay.

**Comment by nylen** [comment]
@mikeschinkel the new constant should go at the beginning of `wp-settings.php`. This is both simpler and will work with existing installs with "legacy" config files.

Please also split the changes for `CORE_PATH` and `CONTENT_PATH` out into a PR. This scope creep is not ideal especially not this close to a release.

**Comment by mikeschinkel** [comment]
@nylen Created PR #242 for the `CORE_PATH` and `CONTENT_PATH` constants.

**Comment by nylen** [comment]
> I do not understand this. `LOAD_CONFIG_ONLY` is needed before `wp-settings.php` is loaded. How can it go in `wp-settings.php`?

Maybe I am missing something here, but I think all that is needed in this PR is to add the following to the beginning of `wp-settings.php`:

```php
if ( defined( 'LOAD_CONFIG_ONLY' ) && LOAD_CONFIG_ONLY ) {
    return;
}
```

**Comment by mikeschinkel** [comment]
@nylen 
> _"but I think all that is needed in this PR is to add the following to the beginning of wp-settings.php:"_

Okay, I see what you are doing, and it is better.

But we will also need to update `wp-load.php` otherwise `wp-settings.php` would never get called when `LOAD_CONFIG_ONLY` is set.

**Comment by mikeschinkel** [comment]
After discussion with @nylen this has boiled down to a simple addition of `require_once( 'wp-settings.php`)` to `require_once( 'wp-load.php`)` in case the developer wants to modify `wp-config.php` to not call `require_once( 'wp-settings.php`)`, which is ideally how WordPress should have been implemented all along.

**Comment by nylen** [comment]
> Maybe I am missing something here, but I think all that is needed in this PR is to add the following to the beginning of wp-settings.php

This comment above was in reference to this specific goal from #197:

> Doing this will make it easier and more reliable for tools like WP CLI to load a site's configuration without having to `eval()` a hacked version of `/wp-config.php`. However, that is only one reason for this.

It's now clear after discussing this change that this was a secondary goal, which I think would be better served by other means.  I'll write up a PR soon, in the meantime here is a suggested implementation:  https://github.com/ClassicPress/ClassicPress/compare/add/load-config-only

I agree this is "ideally how WordPress should have been implemented all along", but I don't think that's a good enough reason to make this change by itself.  I'd like to see an example of a specific problem that this change solves first.

**Comment by nylen** [comment]
Closing, I think this is worth revisiting in the future but hasn't had any activity in a long time.

**Pull request closed without merging**
