### PR TITLE
Optimized all images with ImgBot

### PR DESCRIPTION
**Pull request by Remzi1993**
My apologies for the other PR #456 
@nylen I have fixed the issue with Pull App, this is in another branch. Hardreset won't happen again.

Optimized all images with ImgBot, see: https://imgbot.net and https://github.com/marketplace/imgbot
It's a GitHub App you could install, after installation you could select all or some of your repos to start optimizing images.

### CODE REVIEW

**Comment by nylen** [comment]
Next steps here: https://github.com/ClassicPress/ClassicPress/pull/456#issuecomment-517120871

**Comment by Remzi1993** [comment]
@nylen I will look into it. Maybe this weekend.

**Comment by striebwj** [comment]
This pull request has been mentioned on **ClassicPress Forums**. There might be relevant details there:

https://forums.classicpress.net/t/testing-github-linkback-again/1796/1

**Comment by nylen** [comment]
Closing, it has been a while since this was looked at. We can open a new PR but we need to be careful not to re-optimize the images that are already being optimized as part of our build process.

**Pull request closed without merging**
