### PR TITLE
WP-r52389: Reduce the use of unnecessary randomness in Tests

### PR DESCRIPTION
**Pull request by bahiirwa**
## Description
Code improvements. Fixes https://github.com/ClassicPress/ClassicPress/issues/893

## Types of changes
- [x] Reduce the use of unnecessary randomness in tests.
- [x] Add public to functions with no explicit visibility.

### CODE REVIEW

**Comment by bahiirwa** [comment]
@mattyrob In the newer PRs, we have tests failing because the method names are modified such `tearDown()` becomes `tear_down()`. CamelCase is dropped for snake style.

- Should we introduce this at this stage?
- I need help resolving some of these tests to move forward.

**Comment by bahiirwa** [comment]
> @mattyrob In the newer PRs, we have tests failing because the method names are modified such `tearDown()` becomes `tear_down()`. CamelCase is dropped for snake style.
> 
>     * Should we introduce this at this stage? See https://core.trac.wordpress.org/changeset/51568 in anticipation of [Add support for PHPUnit 7 and 8 #815](https://github.com/ClassicPress/ClassicPress/pull/815)

On second examination, this is resolved in that noted PR.

**Comment by viktorix** [comment]
@mattyrob is this something that v2 tests can benefit from?

**Comment by mattyrob** [comment]
@viktorix - this is already in the `v2` code. As there are conflicts on this PR I would propose we close this.

**Pull request closed without merging**
