### PR TITLE
remove 'Howdy' from admin bar

### PR DESCRIPTION
**Pull request by luizbills**

### CODE REVIEW

**Comment by nylen** [comment]
Hi @luizbills, I find 18 instances of `Howdy` in the code under `src/`.  Let's go ahead and change all of them (and more under `tests/`, but those can be left alone as far as I'm concerned).

Also, in this instance that you changed for the admin bar, let's just remove the word entirely, as discussed on https://vote.classicpress.net/posts/33/replace-howdy-in-the-adminbar this will leave more space for plugins.

**Comment by nylen** [comment]
2018-09-12t22 26 50-05 00

This is a good start, thanks :+1:

We'll finish up these changes in #54.

**Comment by luizbills** [comment]
you are welcome. let's make revolution

**Comment by soulseekah** [comment]
Why? Who voted for this?

**Comment by luizbills** [comment]
@soulseekah read the comments

**Pull request merged**
