### PR TITLE
Add support for WebP image format

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
This is a back-port of multiple upstream changes that add support for the WebP image format.

## Motivation and context
WebP is now supported by modern browsers and ClassicPress should allow users to upload such images.

## How has this been tested?
Unit tests are included as part of the back ported changes.

## Screenshots
N/A

## Types of changes
- New feature

### CODE REVIEW

**Comment by joyously** [comment]
You might want to wait for their fix for the renaming problem (likely scheduled for WP 5.8.1).
[Generated images for one file can be overwritten by another with the same name when mapping mime types for generated images](https://core.trac.wordpress.org/ticket/53668)

And keep an eye on these:
[Media: fix and improve WebP features detection](https://core.trac.wordpress.org/ticket/53663)
[Add capability to set default format for image sub-sizes](https://core.trac.wordpress.org/ticket/52867)
Also, this one might be related: [Media Library shows only the selected image](https://core.trac.wordpress.org/ticket/53765) 
> Seems that it happens only when using the classic editor.

[image conversion from jpg to webp no longer working](https://core.trac.wordpress.org/ticket/53724)

**Comment by mattyrob** [comment]
Testing on PHP 5.6 and 7.0 is failing as WebP images are not supported - these tests should be detecting this already but for some reason, maybe our testing platform configuration, it is slipping through current checks.
Needs deeper review on this point but awaiting further upstream changes so can hold off for now.

**Comment by joyously** [comment]
One more ticket to look at concerns [Javascript and regular expressions for attachments](https://core.trac.wordpress.org/ticket/54146).

**Comment by joyously** [comment]
A new ticket about [[Thickbox gallery does not recognize webp images](https://core.trac.wordpress.org/ticket/55786)](https://core.trac.wordpress.org/ticket/55786) was opened today. I wonder if there are other libraries in core that are limited like that.

**Comment by viktorix** [comment]
This is a large backport. With the upcoming v2, I would say we close this PR.

**Pull request closed without merging**
