### PR TITLE
Set wp-video height to auto to prevent vertical stretching

### PR DESCRIPTION
**Pull request by wolffe**
The `video.wp-video-shortcode` and `.wp-video-shortcode video` elements have no height set, making some videos stretch teh full height of the container, if the container has Flex or Grid siblings.

Basically, if a grid of columns has different height videos inside, the smallest video will stretch to fill the height of the tallest column.

## How has this been tested?

I have tested it with the latest `trunk` version, on 2 ClassicPress installations, one fresh, one with the FX Builder with multiple columns on the page.

### Before

wp-video-before

### After

wp-video-after

## Types of changes

- Bug fix (CSS)

### CODE REVIEW

**Comment by KTS915** [comment]
@wolffe I believe that you have the right approach, but could you provide some HTML so that it's easier to test, please?

**Comment by KTS915** [comment]
@wolffe Yes, very helpful! But now I have a question. Is it better to use `auto` or `100%`? That's a genuine, open question; I don't know the answer.

**Comment by wolffe** [comment]
@KTS915 You are correct to ask, but if you also check images and videos in WordPress, you will notice that the width is `100%`, while the height is `auto`. This is like an older version of aspect ratio, basically the height follows the width. If both are 100%, then they will be stretched to fill the available space.

In my case, they both work, but `auto` makes more sense to me.

Here are some supporting links:

https://www.w3schools.com/css/tryit.asp?filename=tryresponsive_image

https://stackoverflow.com/questions/30631732/why-do-i-need-height-auto-for-responsive-images

**Review by KTS915 — APPROVED** [review]
LGTM

**Pull request merged**
