### PR TITLE
Remove JavaScript and CSS type attributes for HTML5 validity

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
PR for #339 This patch updated tests and removes declarations of `type` when enqueuing or in-lining JavaScript and CSS styles

## Motivation and context
HTML5 should be the standard 4 years after release and official recommendation over previous web standards.

## How has this been tested?
Unit tests are both updated and extended.

### CODE REVIEW

**Comment by pattonwebz** [comment]
What negatives are there to including these (other than the obvious it's out of spec)?

**Comment by nylen** [comment]
> What negatives are there to including these (other than the obvious it's out of spec)?

- It's not necessary any more
- People (myself included) like clean markup
- You can save a few bytes

I think we should accept WP's solution for this now that it's landed over there (see PR #524). This will give us better compatibility and we can also take advantage of the testing they've already done.

**Comment by pattonwebz** [comment]
So no real negatives then? Lol 

So with the proposed patch themes need to update and change their `add_theme_support()` call, right? We should do that automatically for them I think - because knowing how much themes are left as-is I don't see any benefit for the patch in older themes (which is probably where most CP compatible themes come from).

**Comment by mattyrob** [comment]
Closing this PR in favour of #524

**Pull request closed without merging**
