### PR TITLE
Replacing jQuery UI with Sortable JS in Metaboxes

### PR DESCRIPTION
**Pull request by KTS915**
## Description
This PR follows a similar pattern to PR #1265. It replaces jQuery UI's Draggable, Droppable, and Sortable interactions with metaboxes on posts and pages in the admin, and on the main dashboard page with native vanilla JavaScript and  [SortableJS](https://github.com/SortableJS/Sortable), which is widely used and (unlike jQuery UI) under active development.

## Motivation and context
This transition assists accessibility and provides full support for touchscreens. In addition, it speeds up the relevant pages by loading less (and less complex) JavaScript.

I have also taken the opportunity to completely re-write the `postbox.js` file in vanilla JavaScript. It's now much easier to understand instead of the previous esoteric mixture of JS, jQuery, and jQuery UI. So it should be much easier to maintain in the future. It is also much shorter as a result.

## How has this been tested?
I have tested this on my localhost environment, but a significant change like this really needs extensive testing before being merged into core. (I'd hope it can be ready for CP v2.1, but it's certainly not intended for v2.0.)

As with PR #1265 there is a choice to be made about the `forceFallback` option (on lines 149 and 150 of `postbox.js`), namely whether to have it for Safari alone or for all webkit browsers. We need to decide which option to pick and keep it consistent with PR #1265.

## Screenshots
Appearance is unchanged; it is the underlying code that's different.

## Types of changes
- New feature: this is not a breaking change since the jQuery UI modules continue to be bundled with ClassicPress and so available to any theme or plugin that's already relying on its presence; they are just not being used by core here.

### CODE REVIEW

**Comment by xxsimoxx** [comment]
Seems that reordering metaboxes in post does not keep the new order on next page load.
But it's the same in `develop` and also in v1.7.

**Comment by KTS915** [comment]
I'll investigate this. I'm also always open to suggestions for how to correct this.

**Comment by KTS915** [comment]
@xxsimoxx I've just tried again, and it's working for me. I have tried both Firefox and Chrome on Linux.

**Review by xxsimoxx — APPROVED** [review]
It was my fault [here](https://github.com/ClassicPress/ClassicPress/pull/1273#issuecomment-1874083552).
It was a plugin stopping JS.
Looks good!

**Pull request merged**
