### PR TITLE
Removed the PHP <=5.5 compatibility code

### PR DESCRIPTION
**Pull request by chetansatasiya**
## Description

Removed the _(edit: some)_ PHP <=5.5 compatibility code

### CODE REVIEW

**Comment by Mte90** [comment]
I am not sure if it is good to remove code form a library included in the core like SimplePie, what do you think @nylen?

**Comment by nylen** [comment]
It depends on how SimplePie has been kept up to date in WordPress, and whether WordPress has made changes to it apart from SimplePie's own releases.

I agree, we need to look into this more.  If someone can dig up this info that would be great, otherwise I'll try to find it probably early next week.

**Comment by nylen** [comment]
Also, @chetansatasiya, this PR addresses part of #63.  The "Fix: #144" that you wrote in the issue is not correct, because that PR addresses another, different part of #63. I'll edit that now.

**Comment by senlin** [comment]
To be honest I fail to see why @chetansatasiya does a PR of only a handful of files on an issue (#63) that already has someone assigned to it?

**Comment by nylen** [comment]
Yes, it's better to look and see if someone is already assigned before starting work on an issue. If you have questions about the progress or status then you can ask about that on the issue or on Slack.

**Comment by nylen** [comment]
No response to requests for feedback, and the one change that we definitely wanted here has already been made in #151.  Closing this one.

**Pull request closed without merging**
