### PR TITLE
Update nav-menu.php

### LINKED ISSUE #757: PHP 8.0 Bug in `wp-includes/class-wp-query.php`
In `wp-includes/class-wp-query.php`, line 718 needs to be changed from
```
if ( ! is_scalar( $qv['p'] ) || $qv['p'] < 0 ) {
```
to
```
if ( ! is_scalar( $qv['p'] ) || (int) $qv['p'] < 0 ) {
```
This is backwards-compatible with all previous versions of PHP.

_Originally posted by @KTS915 in https://github.com/ClassicPress/ClassicPress/issues/687#issuecomment-860239594_

### PR DESCRIPTION
**Pull request by KTS915**
https://github.com/ClassicPress/ClassicPress/issues/687#issuecomment-860239594

Closes #757

### CODE REVIEW

**Comment by nylen** [comment]
Is this PR based on a WP changeset? If so, the instructions here should be followed to include it in ClassicPress: https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress

Other things that are good to include in PRs like this:

- Links to relevant WP tickets and changesets
- Description of the error this PR prevents, and under what circumstances it may occur (how to see the error on a test install with PHP 8)

**Comment by bahiirwa** [comment]
@nylen @KTS915 I had pushed a backport from WP in https://github.com/ClassicPress/ClassicPress/pull/759 We can evaluate whether the changes are suitable.

**Comment by bahiirwa** [comment]
I have tested it on the front-end following the shared read. Here are my results

## How to replicate:
- Install CP on PHP 8.0 server
- Visit front end of your site.

##Before patch
Screenshot 2021-07-21 at 07 35 17

## After patch
Screenshot 2021-07-21 at 07 35 26

Patch works as mentioned.

**Review by mattyrob — APPROVED** [review]

**Review by mattyrob — APPROVED** [review]

**Comment by mattyrob** [comment]
As discussed at PR review, closing in favour of #759 which covers this issue and seems to be a more complete backport.

**Pull request closed without merging**
