### PR TITLE
Accessibility Improvement: Alt text description

### LINKED ISSUE #539: Accessibility: Alt Text Description Enhancement
##  Context
Currently in CP, we have this(check screenshots) for uploading and editing images

**Editing the image**
Screenshot 2020-02-04 at 12 36 57

**Uploading the image**
Screenshot 2020-02-04 at 12 34 59

WP has moved to this way of communicating the feature to users with a note
> [Describe the purpose of the image](https://www.w3.org/WAI/tutorials/images/decision-tree). Leave empty if the image is purely decorative.

That looks like this:
Screenshot 2020-02-04 at 12 32 20

### Usage 

**Editing the image**

Screenshot 2020-02-04 at 12 31 28

**Uploading the image**

Screenshot 2020-02-04 at 12 33 12

Screenshot 2020-02-04 at 12 32 29

## Possible solution
https://core.trac.wordpress.org/changeset/44900 

Should we implement this? I think it is a nice way of improving Accessibility in CP with a small milestone.

### PR DESCRIPTION
**Pull request by bahiirwa**
Backport Accessibility: improve the "URL" and "Alt text" fields in the media modals. 

Closes #539 

Changeset included: [44900](https://core.trac.wordpress.org/changeset/44900), [45038](https://core.trac.wordpress.org/changeset/45038), [45248](https://core.trac.wordpress.org/changeset/45248)

Screenshots after:

Editing attachment details
Screenshot 2020-02-20 at 13 02 33

On popup modal for uploading the image into CMS
Screenshot 2020-02-20 at 13 02 10

I still find one challenge in the Attachment post edit. Screenshot after Backport has no solution as in the screenshot below.

Screenshot 2020-02-20 at 13 01 47

### CODE REVIEW

**Comment by nylen** [comment]
We need to re-build some of the media library JavaScript, this is probably also why Travis is failing.

You can do this by running `grunt precommit` and then committing the files that change as a result.

> I still find one challenge in the Attachment post edit.

I'm not sure why this would be happening either, but this should be fixed before merging this PR.

**Comment by bahiirwa** [comment]
I have a few issues rising with that.

Screenshot 2020-02-25 at 10 08 43

**Comment by nylen** [comment]
The first issue is because you haven't set up your installation to run the `phpunit` tests. I think you can safely ignore that error for now, but I submitted a PR to make it a bit more clear what is going on: https://github.com/ClassicPress/ClassicPress/pull/566

The second issue is probably because OS X `grep` doesn't support the `-P` flag. I didn't know this, and we should definitely fix it. In the Gruntfile.js line 947 can you change `-P` to `-E` and let me know if that helps? If so, I will submit another PR to fix it.

Finally as a quick fix you should be able to run `grunt precommit:js`, I think that is all that is really needed here.

**Comment by bahiirwa** [comment]
@MarcoZehe You thoughts on this would be appreciated if you get a chance.

**Review by MarcoZehe — APPROVED** [review]
Thanks @bahiirwa for looking into this! I think this would be a good change to have, since alternative text, or missing such alternative text, is a very common accessibility problem. So having these fields here is a good change to help creators deliver more accessible content.

**Comment by bahiirwa** [comment]
@MarcoZehe, I know this is a backport, however, for this section, is this solution exhaustive?

**Comment by MarcoZehe** [comment]
@bahiirwa What do you mean? I cannot see the screenshots, I'm totally blind, so I am not sure what you mean by "this solution" and "this section". I looked through the diff, and it certainly looked both familiar and complete to me from that.

**Comment by bahiirwa** [comment]
The diff check is good. Screen reader check is also fine. Thanks

**Comment by nylen** [comment]
I refreshed the PR and fixed the `grunt precommit` issue from earlier. Let's see if this text shows up in all the places it should now ...

**Comment by bahiirwa** [comment]
Unfortunately @nylen, the edit screen for the media does not have the text. Still is as below.
Screenshot 2021-04-26 at 16 27 10

The other locations have the text.
Screenshot 2021-04-26 at 16 22 09

Screenshot 2021-04-26 at 16 25 00

**Comment by mattyrob** [comment]
@bahiirwa 

I've pulled and tested and indeed this does not show in the `Edit Media` page as accessed by selecting an image in the Media Library and then selecting the `Edit more details` link.

To match upstream changes I believe we need to add the following changes sets to this backport:
https://core.trac.wordpress.org/changeset/45158
https://core.trac.wordpress.org/changeset/45334

**Review by mattyrob — APPROVED** [review]

**Comment by mattyrob** [comment]
I've added the 2 additional changes sets to extend the changes to the Alt Text box to the `Edit Media` page.

Tests are all passing, seems fine to me.

**Review by striebwj — APPROVED** [review]

**Pull request merged**
