### PR TITLE
Add minimum requirements for Themes & Plugins

### LINKED ISSUE #640: Support `Requires PHP:` tag in style.css
We should support `Require PHP` tag in the style.css so that we don't have to create a function to check php versions. This just allows the theme itself to recongized which PHP is required.

### PR DESCRIPTION
**Pull request by bahiirwa**
Fixes #640

As discussed via [slack](https://classicpress.slack.com/archives/CCCF22HG8/p1581690732221300)

As a project, one of the goals is to move forward and have people on more recent PHP versions. 
This is proposal to allow plugins and themes to have a minimum PHP version requirement.

Unlike core which supports PHP 5.6,
- Not all plugins can work on PHP 5.6
- Not all plugin developers want to support PHP 5.6. Some want to only support versions 7+.

This PR comes from [WP ticket](https://core.trac.wordpress.org/ticket/40934).

Adds changesets [47145](https://core.trac.wordpress.org/changeset/47145), [45546](https://core.trac.wordpress.org/changeset/45546), [45185](https://core.trac.wordpress.org/changeset/45185), [44978](https://core.trac.wordpress.org/changeset/44978)

### CODE REVIEW

**Comment by nylen** [comment]
There are still some conflict markers in the comments.  This PR also appears to introduce a new function `validate_plugin_requirements` which is not part of either of the changesets mentioned.

What is left to be done as far as testing this?

**Comment by bahiirwa** [comment]
`validate_plugin_requirements` came in Changeset [44978](https://core.trac.wordpress.org/changeset/44978).

**Comment by bahiirwa** [comment]
Some of the changes in this affect #621. Particular variables like `RequiresWP` and `RequiresPHP` are noted.

**Comment by bahiirwa** [comment]
> `validate_plugin_requirements` came in Changeset [44978](https://core.trac.wordpress.org/changeset/44978).

@nylen Would this be best put as a solo PR? or should I bundle it with this one?

**Comment by bahiirwa** [comment]
Linking to this https://github.com/ClassicPress/ClassicPress/issues/640 as well.

**Comment by timbocode** [comment]
Imho, I think changeset [44978](https://core.trac.wordpress.org/changeset/44978) needs to be bundled into this PR, for the simple reason that the requirements of this PR, as described above, cannot be fully met without the new `validate_plugin_requirements` function.

**Comment by bahiirwa** [comment]
> Imho, I think changeset [44978](https://core.trac.wordpress.org/changeset/44978) needs to be bundled into this PR, for the simple reason that the requirements of this PR, as described above, cannot be fully met without the new `validate_plugin_requirements` function.

That has been done. I also rolled back to be able to have the new changes from `develop` added.

**Comment by bahiirwa** [comment]
Some tests where failing because [45185](https://core.trac.wordpress.org/changeset/45185) was missing but I have since added this.

**Comment by bahiirwa** [comment]
Tests are failing because of an undefined function `is_wp_version_compatible()`.

Might be best to handle this when done with #621 as planned.

**Comment by mattyrob** [comment]
@bahiirwa - At the Slack meeting yesterday I started looking into this and have continued a bit more.

This PR may need a rebase to develop with the following:
```
git checkout themes-plugins-reqs
git fetch upstream
git merge upstream/develop
git push themes-plugins-reqs
```

And then I think as per https://core.trac.wordpress.org/ticket/43992 this PR also needs the following changesets adding:
44979
44981
47573
47574

**Comment by bahiirwa** [comment]
- [x] Add required changesets above. 44979, 44981, 47573, 47574
- [x] More manual tests. See screenshots below.
- [ ] Fix One external PHP version test is failing now.

I created a zip from hello.php with new header items 

```
Requires PHP: 9.0
Requires at least: 8.0
```

## Test Screenshots
### Check for Core version 8.0
Screenshot 2021-12-26 at 10 43 33

### Check for PHP 9.0
Screenshot 2021-12-26 at 10 42 58

**Comment by bahiirwa** [comment]
Did some manual testing on uploading a theme with style.css containing

```
Requires PHP: 9.0
Version: 1.2
```
The upload fails with error message expected.

Screenshot 2022-06-28 at 10 07 04

**Review by xxsimoxx — CHANGES_REQUESTED** [review]
When going to "Add theme" I got 100 x this message:
`Undefined property: stdClass::$requires_php in ...src/wp-admin/includes/ajax-actions.php on line 2943`.
It's checking `$requires_php` in themes that comes from the WP repo API and seems that the value in not set.

**Comment by viktorix** [comment]
With the upcoming v2.0, this PR should be closed.

**Comment by viktorix** [comment]
Closing this PR. Themes/plugins will be revisited once we introduce directory integration.

**Pull request closed without merging**
