### PR TITLE
Use Sortable JS in the admin menus instead of jQuery UI

### PR DESCRIPTION
**Pull request by KTS915**
## Description

jQuery UI provides a series of widgets, interactions, and effects that are used throughout the CP admin pages. It was built to provide tools that HTML4 and XHTML did not provide natively. But HTML5 provides many of these tools, and now that HTML5 is well supported by all modern browsers, it's time to be moving away from jQuery UI, which has had no updates for a decade.

This PR gets the ball rolling by replacing jQuery UI's Draggable, Droppable, and Sortable interactions on the admin menu screen and in the menu panel of the Customizer. Draggable and Droppable are replaced by native vanilla JavaScript. Sortable is replaced by [SortableJS](https://github.com/SortableJS/Sortable), which is widely used and (unlike jQuery UI) under active development.

jQuery UI's Draggable, Droppable, and Sortable modules total about 100kb minified, and they in turn depend on the core module, which weighs in at another 40+kb (on top of jQuery itself). SortableJS weighs in at 44kb minified, and uses only vanilla JavaScript. (I considered using HTML5Sortable, but found that it can't do everything we want, whereas SortableJS can, even though I find its naming conventions somewhat unintuitive.)

## Motivation and context

This transition assists accessibility (even in the Customizer) and provides full support for touchscreens. In addition, it speeds up the relevant pages by loading less (and less complex) JavaScript. (Indeed, I have been able to drop usage of `setTimeout`s in a couple of places because the code is so much faster. In particular, there is no need to constantly re-start SortableJS as there is with jQuery UI's modules.)

I have also taken the opportunity to completely re-write the `nav-menu.js` file in vanilla JavaScript. It's now much easier to understand instead of the previous esoteric mixture of JS, jQuery, and jQuery UI. So it should be much easier to maintain in the future. (I have made only necessary changes to the Customizer, because that's built on `backbone.js` and addressing that is beyond the scope of this PR.)

## How has this been tested?

I have tested this on my localhost environment, but a significant change like this really needs extensive testing before being merged into core. (I'd hope it can be ready for CP v2.1, but it's certainly not intended for v2.0.)

There are some specifics to test and consider:

1. On lines 241 and 242 of `nav-menu.js`, there is a choice of `forceFallback` options for either Safari alone or all webkit browsers. The same choice is on lines 59 and 60 of `customize-nav-menus.js`. We need to decide which option to pick.

2. On the regular menu screen, I have coded it so that dragging is done by clicking on the `move` icon (arrows pointing north, south, east, and west). This avoids issues with activating the `disclosure` (or `details`) widget, which can be opened and closed by clicking anywhere else in the header, except on the title of menu item (though the arrow on the left normally acts as an incentive to click there). We need to get feedback to see if this is a good approach.

3. Whether it is or not, we will need updated instructions where it currently says "Drag the items into the order you prefer. Click the arrow on the right of the item to reveal additional configuration options." and these will need to be translated. One obvious change to be made is that the arrow to which this refers is now on the left!

4. I haven't yet tested this on a touchscreen.

5. Did you know that menu items can be moved around on the admin screen using the arrow keys? I certainly didn't. (In the current implementation, you have to click on the down arrow to make that possible.) This PR makes it so that clicking on the above-mentioned `move` icon will also make it possible to move a menu item using the arrow keys (and this is now supported by proper feedback to screenreader users).

## Screenshot After

Screenshot at 2023-12-02 17-33-26

## Types of changes

New feature.

This is not a breaking change because jQuery is still loaded in the admin menu and Customizer menu panel, and because jQuery UI will still be shipped with ClassicPress so that it can continue to be used both by core on other pages and by users. I intend to follow up this PR with others for widgets and metaboxes, so that we can wean core off jQuery UI, but this is just the start of that process.
-->

### CODE REVIEW

**Comment by mattyrob** [comment]
I haven't tested this is a browser as yet but there are a lot of JavaScript issues that need tidying up in the amended files as per JSHint. Things like undeclared variables, variables that are declared but never used and syntax errors like missing semi-colons at the end of lines.

**Comment by KTS915** [comment]
Ok, thanks, will do!

**Comment by mattyrob** [comment]
A lot of changes in the last 24 hours have many tests now passing.

The last failure to address is a validity check after the build process. In the Gruntfile.js we use JSHint to check the core javascript files, then after the build process that is required to run the complied QUnit tests we make use of j[s-validate](https://www.npmjs.com/package/grunt-jsvalidate) - but this package was last updated 10 years ago and seems not to work well with Javascript past ES5, and this PR includes some ES6.

Solution options are:

1. Exclude the `wp-admin/js/nav-menu.js` file and it's minified version from the js-validate checks
2. Find an alternative to js-validate
3. Attempt to get JSHint working of minified files - however it is more intended for human readable versions
4. Something else I haven't thought of yet!

**Comment by KTS915** [comment]
What does WP do? I know Gutenberg, for example, uses the spread operator.

**Comment by mattyrob** [comment]
> What does WP do? I know Gutenberg, for example, uses the spread operator.

WordPress and also Gutenberg are using build steps with things like wepback and babel, particularly with Gutenberg as it is mainly written in JSX. Babel for example has a set of plugins specifically for more modern constructs like [spread](https://babeljs.io/docs/babel-plugin-transform-spread) and the code in compiled for distribution.

The js-validate step simply checks built javascript files for syntax errors, whereas JSHint does that and also checks formatting for easier readability in the code.

**Comment by KTS915** [comment]
Just came across this [changeset](https://core.trac.wordpress.org/changeset/56247), where WP dropped jsvalidate task from Gruntfile to "simplif[y] the build and avoid[] false-positive warnings where the outdated tool flags modern JS syntax incorrectly."

**Comment by mattyrob** [comment]
> Just came across this [changeset](https://core.trac.wordpress.org/changeset/56247), where WP dropped js-validate task from Gruntfile to "simplif[y] the build and avoid[] false-positive warnings where the outdated tool flags modern JS syntax incorrectly."
> 
> It also says it was originally introduced to catch errors caused in IE by the minification process. As we don't support IE any more than WP does, I'm thinking we can simply drop js-validate too.

Interesting and well done on finding that change. It does seem to be an extra and maybe unnecessary step and there does not seem to be a more up to date and easy replacement so removing seems like the only way forward to allow us to use more modern javascript.

**Comment by mattyrob** [comment]
Can the JSHint error in `src/wp-admin/js/nav-menu.js` be fixed by removing the `position` variable from the `var` list and then on the next line:

```
position = position || [ ...editMenu.querySelectorAll( 'li' ) ].indexOf( itemToRefresh );
```

Does it still work the same? I'm guessing so but would need steps provided to adequately test.

**Comment by KTS915** [comment]
@mattyrob Yes, it works just the same. I'll patch the PR right now.

**Review by xxsimoxx — APPROVED** [review]
LGTM

**Pull request merged**
