### PR TITLE
Remove hello dolly plugin

### PR DESCRIPTION
**Pull request by luizbills**

### CODE REVIEW

**Comment by nylen** [comment]
It looks like a good number of tests need to be updated with this change too.

A better approach may be to exclude `hello.php` from the build process, but leave it in the source tree.

**Comment by senlin** [comment]
One of the tests contains a function `test_update_plugin()` that tests updating Hello Dolly, so that will need to be removed too I think.

https://github.com/ClassicPress/ClassicPress/blob/master/tests/phpunit/tests/ajax/UpdatePlugin.php#L133-L168

**Comment by senlin** [comment]
And _testing `wp_enqueue_code_editor with file path`_ will have to be removed too.

https://github.com/ClassicPress/ClassicPress/blob/master/tests/phpunit/tests/dependencies/scripts.php#L728-L813

@nylen is it an additional risk if tests like that are going to be skipped?

**Comment by Mte90** [comment]
No we need that test because use hello dolly to check if the internal system to check updates etc is working.

So we have two option:

* leave hello dolly on classicpress but remove on the release of the official package
* use another plugin that the project will include

The tests use a unique php file because is more fast and is already available, download one can slow down tests.

**Comment by senlin** [comment]
I remember someone wrote a silly hello-dolly replacement for ClassicPress. Maybe we can use that for the tests instead and then indeed remove exclude `hello.php` from the build process as @nylen already suggested above.

**Comment by Mte90** [comment]
Agree, so we need to wait before merge to this and see the hello dolly replacement :-)

**Comment by senlin** [comment]
I'm looking for it now..., and this cannot be merged anyway as all the Travis-CI tests have failed

**Comment by senlin** [comment]
I think it has been removed, there is still a reference on Google though:

classicpress hello dolly - google search-180912

**Comment by Mte90** [comment]
That link go to a 404

**Comment by senlin** [comment]
> That link go to a 404

exactly, that is why I asked him why he removed it :)
the readme file is still on googlecache: http://webcache.googleusercontent.com/search?q=cache:https://github.com/marctenax/hello-classic

the rest is not unfortunately.

**Comment by nylen** [comment]
We probably don't need to change Hello Dolly, just exclude it from the build process.

@luizbills are you going to update this PR, or shall we close it?

**Comment by luizbills** [comment]
@nylen you can close. I'm not very familiar with the build process

**Pull request closed without merging**
