### PR TITLE
Deprecate 'wp-api' script

### PR DESCRIPTION
**Pull request by KTS915**
We discussed at length whether to take out some parts of ClassicPress and put them into core plugins. In the end, we decided not to do so, but to remove Post by Email functionality altogether in CP v3.0.

I think, however, that there is something else we should remove, and that is the `wp-api` script. This is part of the REST API but, like Post by Email, has become obsolete and I haven't been able to find anything that uses it. Core certainly does not.

This script was originally the basis of the REST API, but it soon became clear that it was too difficult to use because it depends on `backbone.js`, which almost no-one understands. As a result, development on the REST API switched to using PHP, and a new script, `wp-api-request`, was developed to take the place of `wp-api` and act as the API's bridge between PHP and JavaScript.

We should, therefore, deprecate the `wp-api` with a view to removing it altogether in CP v3.0. If there are any plugins that use it — and there won't be many, if any — this will give their developers a chance to modify their code. If we don't do this, we'll effectively be committing to supporting this script, which we clearly have no interest in doing.

### CODE REVIEW

**Comment by xxsimoxx** [comment]
Wondering if `_deprecated_argument( 'wp_enqueue_script', 'CP-2.2.0', $message );` (and the same for styles) should be
`_deprecated_argument( 'wp_enqueue_script', 'CP-2', $message );` or something else.

**Comment by KTS915** [comment]
Good point about `_deprecated_argument`! How about `'CP-2.2.0/CP-2.3.0'`?

**Comment by xxsimoxx** [comment]
Maybe the best way is something like
```
'hoverIntent' => 'CP-2.2.0',
'wp-api'      => 'CP-2.3.0',
```
and change `_cp_deprecate_wp_enqueue_scripts()` to achieve this.

**Comment by mattyrob** [comment]
@KTS915 - what do you think of the proposed from @xxsimoxx to use an associative arrange for the deprecation library and version? I can update the PR in this way if you wish.

**Comment by KTS915** [comment]
@mattyrob Go ahead!

**Review by KTS915 — COMMENTED** [review]
Just a really nitpicky formatting change (sorry!) In line 1691,
```
foreach ( $deprecated_scripts as $deprecated_script => $version) {
```
needs to be changed to:
```
foreach ( $deprecated_scripts as $deprecated_script => $version ) {
```

**Review by KTS915 — COMMENTED** [review]
LGTM.

**Review by xxsimoxx — APPROVED** [review]
Works as intended.

**Pull request merged**
