### PR TITLE
Fixed theme update notices (overlapping, fixed height and excessive length)

### PR DESCRIPTION
**Pull request by Norskes**
## Description
1. Wrapped notices with a common "div.notices". Notices now have responsive height and no top margin. External positioning is provided by a wrapper. (According to discussion: https://github.com/ClassicPress/ClassicPress/issues/414#issuecomment-505707842)
2. Wrapped secondary parts of related long messages to hide them on mobile (native breakpoint is 1120px).
3. Added __() to some strings that had no internalization. 

## Motivation and context
Issue, help wanted: https://github.com/ClassicPress/ClassicPress/issues/414
Proposal: https://github.com/ClassicPress/ClassicPress/issues/414#issuecomment-506892952

## How has this been tested?
Visually tested changes in Chrome and Firefox. First at full witdh then decreasing viewport to activate breakpoint. Tested in English and Russian locales + adding hypothetical additional length

## Screenshots (if appropriate):
Desktop, FF:
image
Mobile, Chrome:
image
Mobile, FF:
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by nylen** [comment]
Thanks for the PR, the direction here looks good.

There is one more place that probably needs to be updated - these notices can also appear in the Customizer:  https://github.com/ClassicPress/ClassicPress/pull/385/files#diff-ad7d9b797ea9279bf01bf89b72af6d8fR101

Needs detailed review & testing but I think it is pretty much there.

**Comment by nylen** [comment]
@Remzi1993 : What testing were you able to do here?

**Comment by Remzi1993** [comment]
@nylen I did not run tests specifically, just installed this branch with PHP display_errors = on
I think this is not enough testing, so I let you decide.

**Comment by Norskes** [comment]
Just copying here the latest review notes from Slack (by @nylen), for history.

First task:
> I think we should pull the `<span class="cut">` out of the translated strings and split the translations in two pieces. this will avoid any HTML in the translations which is a plus. We will have to re-translate this string anyway
> `New version available. <button class="button-link" type="button">Update now</button>`
> yeah, we'll have to re-translate everything, no way around that

Second task:
> the other thing we should do is make all the messages consistent
> so we should end up with `__( 'New version available.' )` and `__( 'Update now' )` with the appropriate HTML wrapping them
> and `__( 'Use the "%s" child theme instead!' )` and `__( 'This is a parent theme that says "Powered by WordPress" in its footer.' )` also separated, with a `<span class="cut">` wrapping the one that should be hidden on mobile
> and that structure should be exactly the same on each of the 3 places where this code comes into play

Third task:
> I think we should also tweak the breakpoints a bit
> instead of having the .cut hide itself at `1120px`, hide it at 780px
> this matches the breakpoint where the admin menu disappears
> and probably something slightly different in the customizer, since there is a spot around 1000 or 1100px where the theme boxes look very small

Will do this today.

**Pull request merged**
