### PR TITLE
WP-r50784: Build/Test Tools: Remove Internet Explorer 11 from the `browserslist` (837)

### LINKED ISSUE #837: Drop support for IE11
IE11 is far below 1% usage now, so it's time to drop it and backport changes from WordPress. [Discussion](https://forums.classicpress.net/t/classicpress-browser-support/815/).

## Expected behavior
IE11 no longer supported.

## Current behavior
IE11 supported.

## Possible solution
Backport changes from WordPress.

- https://core.trac.wordpress.org/ticket/52941
   - https://core.trac.wordpress.org/changeset/51146
   - https://core.trac.wordpress.org/changeset/51212
- https://core.trac.wordpress.org/ticket/53077
   - https://core.trac.wordpress.org/changeset/50784
- https://core.trac.wordpress.org/ticket/53078
   - https://core.trac.wordpress.org/changeset/50934

And a notice to discourage IE11 use:
- https://meta.trac.wordpress.org/ticket/4863
   - https://meta.trac.wordpress.org/changeset/9446

I think that covers it. If anyone knows of any other tickets or changesets, please do comment.

### PR DESCRIPTION
**Pull request by viktorix**
## Description
Resolves #837 by backporting 50784.

This officially removes support for Internet Explorer 11 in the CSS files run through the build process in Core.

Individual tickets should be opened for removing each manually maintained area of the code base targeting IE11.

The resulting changes to CSS files are included in this commit.

Fixes https://core.trac.wordpress.org/ticket/53077.

Conflicts:
    - package.json
    - src/wp-admin/css/about.css
    - src/wp-admin/css/admin-menu.css
    - src/wp-admin/css/common.css
    - src/wp-admin/css/customize-controls.css
    - src/wp-admin/css/customize-nav-menus.css
    - src/wp-admin/css/customize-widgets.css
    - src/wp-admin/css/list-tables.css
    - src/wp-admin/css/login.css
    - src/wp-admin/css/site-health.css **(not in CP)**
    - src/wp-admin/css/themes.css
    - src/wp-admin/css/widgets.css
    - src/wp-includes/css/media-views.css

---
Merges https://core.trac.wordpress.org/changeset/50784 / WordPress/wordpress-develop@e4bda140d4 to ClassicPress.

## Motivation and context
IE11 usage is under 1%.

## How has this been tested?
Backport. The changeset removes -ms properties in stylesheets and removes IE from the .browserlist.

## Types of changes
Feature removal

### CODE REVIEW

**Comment by mattyrob** [comment]
@viktorix - This looks broadly fine - just some conflicting code left in `src/wp-admin/css/list-tables.css` to be addressed.

**Comment by viktorix** [comment]
@mattyrob Thanks. I've fixed it. Removed the remaining 2 merge conflict changes that were not part of the changeset.

**Review by mattyrob — APPROVED** [review]

**Comment by mattyrob** [comment]
This looks good, seems may just need `grunt precommit` running locally with a further commit now.

**Comment by viktorix** [comment]
@mattyrob I forgot to ask, how can I run `grunt precommit` locally? Any instructions? I believe James ran it for me on a previous PR.

**Comment by mattyrob** [comment]
@viktorix - if you already have `nom` available locally, according to the [grunt documentation](https://gruntjs.com/using-the-cli) you should be able to run this command to make the grunt-cli available:
`npm install -g grunt-cli`

The `-g` makes the grunt-cli command available globally. After that you can check it has worked with `grunt --version` which will hopefully report the version number. Then you can go ahead and run `grunt recommit` and push the changes.

**Comment by viktorix** [comment]
@mattyrob I got everything set up for grunt, but when I try to run it inside CP directory I get this:
```
$ grunt recommit
grunt-cli: The grunt command line interface (v1.4.3)

Fatal error: Unable to find local grunt.
```

**Comment by mattyrob** [comment]
It seems that `grunt-cli` is present but `grunt` is missing, try:
```
npm install -g grunt
grunt recommit
```

**Comment by viktorix** [comment]
@mattyrob Grunt was installed, but not locally. I found instructions on the getting started page which said I need to run `npm install` to install necessary packages. Which I did. Then running `grunt precommit` gave me the following error:

```
PS C:\WinNMP\WWW\ClassicPress> grunt precommit
Running "rollup" task
Fatal error: C:\WinNMP\WWW\ClassicPress\node_modules\.bin\rollup:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by viktorix** [comment]
@mattyrob this may be related to Windows. I created an issue to keep this conversation separate from the PR:
https://github.com/ClassicPress/ClassicPress/issues/854

**Comment by mattyrob** [comment]
@viktorix - well that's frustrating, leave it with me, I'll see if I can pull this branch and run the `grunt precommit` here and push those changes.

**Pull request merged**
