### PR TITLE
Removes the Security Page Menu ref: #1014

### PR DESCRIPTION
**Pull request by smileBeda**
ref: #1014

### CODE REVIEW

**Comment by viktorix** [comment]
@smileBeda would it be possible for you to update code so it passes coding standards? Just a few spaces and indents. We'll include it in 1.6.0.

**Comment by smileBeda** [comment]
That is weird, I _do_ use WPCS. And the failed check above (its logs) say the log is expired so I can't really see what the complaint of the sniffer is.

Can we somehow find out what the exact complaints of the sniff are? Again, I do have the WPCS installed and generally it does a good job. What is possible is that it meshed it up due to my local settings versus githubs, but then again, my local settings use what WPCS suggests 

If I can know _what_ I need to change, I will of course do it!

**Comment by viktorix** [comment]
Under the "Files Changed" tab, it lists the issues line by line. Does this help?

image

**Review by xxsimoxx — APPROVED** [review]
Tested using [Vars](https://github.com/xxsimoxx/vars), a plugin that uses the security page.

**Review by mattyrob — APPROVED** [review]

**Pull request merged**
