### PR TITLE
Rename WordPress to ClassicPress: Update all `@since` annotations

### PR DESCRIPTION
**Pull request by nylen**
WordPress uses `@since` annotations in the code to indicate the version when a function or feature was introduced, removed, modified, etc.

Since we'll be starting ClassicPress with version `1.0.0` (discussion in Slack today; summary coming soon), we need to update these references to make the differences between WP and CP versions clear.  I've done this by changing `@since 2.0.0` to `@since WP-2.0.0`.

### CODE REVIEW

**Comment by stefanos82** [comment]
@nylen, GitHub does not escape @ character either with backticks or with backslash; therefore you accidentally included user SInCE as part of your commits, unless you have done so consciously.

If indeed it was by mistake, try next time the following format for just in case: 
```
`@-since`
```

I have tested it and it works just fine; the hyphen stops the parser from searching for candidate user as you type.

**Comment by nylen** [comment]
This is what I did; apparently it does not work for commit messages.

**Comment by stefanos82** [comment]
Been there, done that mate; I know the pain :disappointed:

The only way to make it work is to add a hyphen between `@` and your name / variable / you-name-it.

**Comment by nylen** [comment]
By the way, it'd be cool to have you on [our Slack group](https://join.slack.com/t/classicpress/shared_invite/enQtNDIwNjY2OTg1MjAxLWJiM2U2NmY3ZjFlZjQ4Zjk2OGI4ZTg3NzY1ZTU3NzI3OTRjMTU0YzAzOWUyZmZlODgyOWE1YTViYjcwY2Y5YzI) if you're not already :)

**Comment by stefanos82** [comment]
I just registered.

**Pull request merged**
