### PR TITLE
WP-r43581: TinyMCE: remove stray CSS map reference from `skin.min.css`.

### PR DESCRIPTION
**Pull request by nylen**
This was causing a warning reported in Slack:

>The style sheet located at `/wp-includes/js/tinymce/skins/lightgray/skin.min.css` is minified, so, it's has a source map reference at the end
>`/*# sourceMappingURL=skin.min.css.map */`
>Because the source map file doesn't exist it's throwing an error in Firefox (probably others, as well)
>
>```
>Source map error: request failed with status 404
>Resource URL: https://localhost/ClassicPress/wp-includes/js/tinymce/skins/lightgray/skin.min.css?wp-mce-4800-20180716-tadv-4.7.13
>Source Map URL: skin.min.css.map
>```

Fixed upstream, see: https://core.trac.wordpress.org/ticket/44785#comment:5

This PR merges https://core.trac.wordpress.org/changeset/43581 / WordPress/wordpress-develop@28dcba340c to ClassicPress.

### CODE REVIEW

**Comment by nylen** [comment]
Sure thing... the Travis build is going to need some fixing before we can merge it though (see #413).  In this case I know the failure is unrelated, but we don't need this urgently so let's not merge anything with a failing build.

**Comment by johnalarcon** [comment]
That sounds like a good plan.  Thanks for the update.

**Comment by nylen** [comment]
The build is fixed now, so I'm merging this. It's set for the next minor release which will be out sometime in June or July.

**Comment by johnalarcon** [comment]
Ah, I see ClassyBot referenced the forum post... It seems this issue is back in version 1.2.0.

**Pull request merged**
