### PR TITLE
remove hello dolly. 

### PR DESCRIPTION
**Pull request by haykuro**
per: https://vote.classicpress.net/posts/1/remove-the-hello-dolly-plugin

*Description:*
A few folks were asking we remove the hello dolly plugin by deafult.

*Changes Made:*
- I've deleted the empty unit test and the plugin from the repo.

### CODE REVIEW

**Comment by nylen** [comment]
Previously: https://github.com/ClassicPress/ClassicPress/pull/50

Hello Dolly is used in some automated tests for WP plugins in general, and I think this PR will fail the unit tests, like that first one did.

We need to come up with an approach that will keep the tests passing.  One idea is to leave Hello Dolly in the source tree, but exclude it from the build.

**Comment by haykuro** [comment]
I see this requires a bit more work..

```
tools/i18n/makepot.php
255:		$result = $potextmeta->append( "$dir/wp-content/plugins/hello.php", $output );

tests/phpunit/tests/dependencies/scripts.php
735:		$real_file = WP_PLUGIN_DIR . '/hello.php';

tests/phpunit/tests/admin/includesPlugin.php
8:		$data = get_plugin_data( DIR_TESTDATA . '/plugins/hello.php' );
61:		activate_plugin( 'hello.php' );
62:		$test = is_plugin_active( 'hello.php' );
65:		deactivate_plugins( 'hello.php' );
69:		deactivate_plugins( 'hello.php' );
70:		$test = is_plugin_active( 'hello.php' );
75:		deactivate_plugins( 'hello.php' );
76:		$test = is_plugin_inactive( 'hello.php' );
81:		activate_plugin( 'hello.php' );
82:		$test = is_plugin_inactive( 'hello.php' );
85:		deactivate_plugins( 'hello.php' );
92:		$name = 'hello.php';
283:		$this->assertFalse( is_network_only_plugin( 'hello.php' ) );
301:		$name = 'hello.php';
311:		$name = 'hello.php';

tests/phpunit/tests/multisite/network.php
249:		$path = "hello.php";
261:		$this->assertEquals( Array(WP_PLUGIN_DIR . '/hello.php'), $active_plugins );
280:		$path = "hello.php";
300:		activate_plugin( 'hello.php', '', true );
301:		$this->assertTrue( is_plugin_active_for_network( 'hello.php' ) );
305:		deactivate_plugins( 'hello.php', false, true );
306:		$this->assertFalse( is_plugin_active_for_network( 'hello.php' ) );

tests/phpunit/tests/ajax/UpdatePlugin.php
137:		$_POST['plugin']      = 'hello.php';
158:				'plugin'       => 'hello.php',

src/wp-admin/includes/plugin.php
135:		} elseif ( 'hello.php' == basename( $plugin_file ) ) {
```

**Comment by senlin** [comment]
@haykuro - by excluding the plugin from the tests, these will fail, so instead of rewriting the tests (lots of work) or rewriting the plugin (waste of time), we have decided that for now the plugin needs to stay in the tests. 

So what we're really after is a way to exclude it from the build. The build is putting together a downloadable package that can be installed by people, same as people can visit the WP website and download the most recent version.

As we don't know exactly yet how to put this build together, we also don't know how to exclude hello dolly and akismet from it, but this might actually be easier than we initially thought.

So the first step would be to remove the condition you referred to here: [here](https://github.com/ClassicPress/ClassicPress/blob/master/tools/i18n/makepot.php#L255-L258) and [here](https://github.com/ClassicPress/ClassicPress/blob/master/src/wp-admin/includes/plugin.php#L135-L137)

**Comment by nylen** [comment]
> we have decided that for now the plugin needs to stay in the tests.

Or some other approach that keeps the tests passing, but removes the plugin from `wp-content/plugins`.   Perhaps it can be installed from a different location (the test suite could copy it to the plugins directory when it's needed, and delete it after).

**Comment by nylen** [comment]
See also #122 and #74

**Pull request merged**
