### PR TITLE
Added 7nth Parameter $position to add_submenu_page

### PR DESCRIPTION
**Pull request by smileBeda**
## Description
Added the ability to define submenu position in `add_submenu_page()`.
Possible values are numeric integers or float.
Throws a "Doing it wrong" if anything else is passed.

## Motivation and context
I was creating a Plugin for ClassicPress, wanted to define its menu position and saw it is not possible. Realised the `add_submenu_page()` function only supports the menu position since 5.3, see https://developer.wordpress.org/reference/since/5.3.0/

## How has this been tested?
On local install with Plugin using this new feature (and also not using it, and using it wrongly), with WP Debug turned on.

## Screenshots
Without the feature - menus are pushed to last position
With the feature, this is position 3 passed

## Types of changes
- New feature (in CP. It is an existing feature in WP)

### CODE REVIEW

**Review by xxsimoxx — CHANGES_REQUESTED** [review]
Indentation is using spaces while other functions uses tabs.

Other than that it works good for me.
Before:
Schermata 2022-06-06 alle 15 56 10
After:
Schermata 2022-06-06 alle 15 55 47

**Comment by TukuToi** [comment]
Thanks, I think it is because I edited it on Git Directly.
In any case, looking good but I cannot accept the change, as I am the author of the PR :(

Needs thus review from a third (and fourth) person to accept your indentation amendments.

**Comment by TukuToi** [comment]
I'm sorry, I was looking at my own commit 🙄 
This should be corrected now to use tabs.

**Comment by bahiirwa** [comment]
From [WP File blame](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php?annotate=blame) these are some of the changesets for the amendments.

https://core.trac.wordpress.org/changeset/42394
https://core.trac.wordpress.org/changeset/46197
https://core.trac.wordpress.org/changeset/46198
https://core.trac.wordpress.org/changeset/51955
https://core.trac.wordpress.org/changeset/52035
https://core.trac.wordpress.org/changeset/53104
https://core.trac.wordpress.org/changeset/53264

**Comment by mattyrob** [comment]
Re-opening as this is a good change to consider for CP Core

**Review by xxsimoxx — APPROVED** [review]
Looks good.
Also tested the `_doing_it_wrong`
### Before
Schermata 2022-09-19 alle 09 31 24
### After
Schermata 2022-09-19 alle 09 31 08

**Comment by bahiirwa** [comment]
Unfortunately `smileBeda:patch-6` branch has been deleted and needs to be restored as we did with https://github.com/ClassicPress/ClassicPress/pull/1109

**Comment by mattyrob** [comment]
Closing in favour of #1128 where we can handle any future conflicts more easily.

**Pull request closed without merging**
