### PR TITLE
Better process for listing/building Twemoji

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
First attempt at fixing #447

## Motivation and context
As detailed in the issue filed, move away from lists Emoji files with svn command

## How has this been tested?
Through testing I've made sure the URLs are currently called and parsed, resulting Emoji code is created when the grunt task is executed, could do with some more eyes on the result to check it is working as expected.

4 Emojis worked as expected locally. but it's a dev environment so needs more checking.

## Types of changes
- Bug fix / Enhancement

### CODE REVIEW

**Comment by mattyrob** [comment]
This will fail building as there are 3 new emoji codes on the GitHub repo that are not currently included in the formatting.php file - manual comparison of the files now shows a high level of data reproduction with this new method.

**Comment by nylen** [comment]
This code is very deeply indented, and a bit redundant, so let's refactor this a bit, and create 2 functions at the top of the Gruntfile. They could be called something like `listTwemojiAssets` and `callGitHubAPI`. The second function should contain all of the error handling for a GitHub API call to avoid repeating it. We should also avoid calling `curl` since it may not be installed, and Node.js can do this just fine.

Doing this "correctly" would mean changing these functions from synchronous to asynchronous. I looked at the existing https://github.com/outaTiME/grunt-replace and also https://github.com/gruntjs/grunt-contrib-copy as a possible alternative, and didn't see a way to make an asynchronous function work with either of these grunt tasks. So doing the HTTP requests using https://github.com/ForbesLindesay/sync-request is probably the easiest way to make this work without requiring `curl`.

---

One big advantage of this approach is that we can now pin the listing to a specific commit.

This commit should be from the `gh-pages` branch, currently the commit hash should be this one https://github.com/twitter/twemoji/commit/6f3545b9649bba68ead0660328f318777c8a9416 which makes the initial API URL the following: https://api.github.com/repos/twitter/twemoji/commits/6f3545b9

This commit is a bit outdated but it matches the Twemoji version we've been using since #421. With this change the build should pass again.

At some point we should probably change this logic to use the `twemoji` repository's named tags on the `master` branch, as this PR has started to do, but let's save that for a separate PR. This will also require updating twemoji.classicpress.net, the repository used for that subdomain has a bit more relevant info too: https://github.com/ClassicPress/twemoji-assets

**Comment by mattyrob** [comment]
Some changes made but I'm down a rabbit hole trying to switch to use the `gh-pages` tree. :(

**Comment by mattyrob** [comment]
@nylen 

I've made some changes starting with abstracting the HitHub API calls and error handling.

Im trying to switch branch to:
`https://api.github.com/repos/twitter/twemoji/branches/gh-pages`

From there to the tree repo:
`https://api.github.com/repos/twitter/twemoji/git/trees/b7487752232cb24fa3d5daed7a80920cc491ce61`

From there I've tried the `/svg/` and `/2/svg/` but both give different results than expected in the `src/wp-includes/formatting.php` file. Am I looking in the wrong place or have other changes been committed making the current entries obsolete?

**Comment by nylen** [comment]
> have other changes been committed making the current entries obsolete?

This is always a possibility, so we should be starting with a specific commit hash instead of a branch name. That commit hash should currently be https://github.com/twitter/twemoji/commit/6f3545b9649bba68ead0660328f318777c8a9416

> On further investigation it seems the 2 arrays in the `src/wp-includes/formatting.php` are the same in terms of contents but in a different order. I suspect that the file names are the same once processed but are in the directory listing in a different order.

Interesting. I suppose we can either make this match the old order, or (1) confirm that changing the order in this way won't break anything and (2) confirm that the filenames are all the same except for order.

**Comment by mattyrob** [comment]
I've restored the `Gruntfile.js` from the `develop` branch as a test, in my debugging the original code and my patch produce identical output so I can't figure out why the tests fail.

The GitHub API is a much faster way of producing the emoji arrays in my experience.

I'm currently parsing the following URLs:
`https://api.github.com/repos/twitter/twemoji/branches/gh-pages`
`https://api.github.com/repos/twitter/twemoji/git/trees/b7487752232cb24fa3d5daed7a80920cc491ce61`
`https://api.github.com/repos/twitter/twemoji/git/trees/170306d4175256d9985cb912b45a7889704f66bc`
`https://api.github.com/repos/twitter/twemoji/git/trees/89344e16fc3eb7c7f3584a3cda03f34d04d4f51a`

**Comment by mattyrob** [comment]
@nylen 

This PR is driving me mad, it's not passing the Travis checks, but...

I've just noticed that if I use the develop branch without any changes made and call the existing `grunt replace:emojiRegex` command, that is making changes to the `src/wp-includes/formatting.php` file.

So, I'm starting to think there isn't an issue with the PR as the output on this branch for the old function and my PR is identical now.

**Comment by nylen** [comment]
> we should be starting with a specific commit hash instead of a branch name

You seem to be missing this part still. This means you should start with https://api.github.com/repos/twitter/twemoji/commits/6f3545b9 instead of https://api.github.com/repos/twitter/twemoji/branches/gh-pages, as I've written above.

**Comment by mattyrob** [comment]
I can make a commit with that URL but is still makes changes to wp-includes/formatting.php locally in my testing despite a `grunt.file.write()` call dumping `entities` variable to a text file returning identical strings using the current replace:emojiRegex code and my amended version.

**Comment by nylen** [comment]
OK, go ahead and make that commit, and if you want, I will take a look and see if I can fix it.

**Comment by mattyrob** [comment]
@nylen 

Changes committed and the build checks still fail :(

I'm not sure what else it can be unless a different emoji commit has been used for the current `formatting.php` file entities.

**Comment by nylen** [comment]
I dumped the contents of the `entities` and `partials` arrays out to text files before and after this PR. Here are the line counts in each file:

```
$ wc -l *.txt
 3073 entities-before.txt
  872 entities-after.txt
 1311 partials-before.txt
  872 partials-after.txt
```

As you can see, there are a bunch of missing entries. I think what is going on is that a git tree is not a directory listing, instead, it's a listing of the files changed/updated in a given commit. Without digging into the details of how git organizes its objects, which I don't really know, there is a clue at https://stackoverflow.com/a/25023044:

> This will have to be relative to a particular commit, as some files may be present in some commits and absent in others

So I think unfortunately this approach is a dead-end, and the only way to fix this is https://github.com/ClassicPress/ClassicPress/issues/447#issuecomment-511167113.

**Comment by nylen** [comment]
>unfortunately this approach is a dead-end

This part sucks, but the code structure here is still good. We'll still need to use `sync-request` for example.

So if it's ok with you, let's leave this PR open until we have a chance to implement our own API endpoint for this.

**Comment by nylen** [comment]
@mattyrob I went ahead and fixed it, the latest commit should pass the build.

See also the new API endpoint added here: https://github.com/ClassicPress/ClassicPress-APIs/tree/master/twemoji

I've added some debug code to verify the emoji list. You can use it as follows:

```sh
# after this branch is merged, before making a change
DEBUG_TWEMOJI_FILES=before grunt precommit:emoji
# after making a change
DEBUG_TWEMOJI_FILES=after grunt precommit:emoji
```

I've used this code (and a close equivalent for before these changes) to verify that the only thing that changed is the sort order of some of the emoji, the list is still the same.

Finally here is the result of a test of some of the emoji that changed sort orders:

- `&#x1f9d1;&#x1f3ff;&#x200d;&#x1f91d;&#x200d;&#x1f9d1;&#x1f3ff;`
- `&#x1f3cb;&#x1f3fb;&#x200d;&#x2640;&#xfe0f;`

2019-10-07T20-09-48Z

**Comment by nylen** [comment]
Thank you, for getting this started! This will provide a way forward for several things in the future:

- Upgrading the Twemoji version when we want, without having to worry about unexpected changes due to pulling from the latest commit of a branch
- Pulling more parts of the build logic out into separate files, the Gruntfile is still over 1000 lines which is pretty long!
- Splitting the emoji process out into a core plugin for v2.

For now I think we are good to go, so I'm going to merge this as a good next step.

**Pull request merged**
