### PR TITLE
Add Github Action Workflow Badges

### PR DESCRIPTION
**Pull request by striebwj**
Replaces the Travis badge with the Github Actions Workflow badges, based on the `develop` branch.

### CODE REVIEW

**Comment by timbocode** [comment]
Just a thought. I wonder if it might be neater if each button linked to the corresponding Actions page?

For example, the Coding Standard markdown would be something like this:

`[Coding Standards](https://github.com/ClassicPress/ClassicPress/actions?query=workflow%3A%22Coding+Standards%22)`

which would produce this:

[Coding Standards](https://github.com/ClassicPress/ClassicPress/actions?query=workflow%3A%22Coding+Standards%22)

As I say, just a thought.

**Comment by striebwj** [comment]
@timbocode definitely better, I don't know why the default is just opening the badge up in a new tab... I will push a tweak in a bit

**Comment by striebwj** [comment]
Added the links to the badges 👍

**Review by nylen — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
