### PR TITLE
Fix/php74 compatibility

### LINKED ISSUE #494: PHP 7.4 compatibility
## Expected behavior
No errors/notices in PHP 7.4.

## Current behavior
Unknown but almost certainly not fully compatible.

## Possible solution
Backport relevant changes from WordPress. Here is a list so far (not complete):

- https://core.trac.wordpress.org/changeset/46112 Update getID3 library to fix issues with PHP7.4
- https://core.trac.wordpress.org/changeset/46113 Comment out magic quote functions [in getID3 library]
- https://core.trac.wordpress.org/ticket/48046 Add array cast before `count()` in class-wp-xml-server.php (this is really for PHP 7.3)

And tangentially related:

- https://core.trac.wordpress.org/ticket/48041 Add PHP info to travis output
- https://core.trac.wordpress.org/changeset/46149 Remove redundant PHP 4 code from `do_action()`

## Steps to reproduce (for bugs)

Verify that all affected code paths are covered by automated tests (the XML-RPC one probably isn't) and look at the Travis CI build output.

### PR DESCRIPTION
**Pull request by bahiirwa**
This PR seeks to Closes #494 by backporting the WP changes in the PHP 7.4 Compatibility fixes.

Changesets ported: 
[A full list of tickets related to PHP 7.4 support can be found on Trac.](https://core.trac.wordpress.org/query?keywords=~php74&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&order=priority)
[47783](https://core.trac.wordpress.org/ticket/47783) - phpmailer
[46112](https://core.trac.wordpress.org/changeset/46112) - Update getID3 library to fix issues with PHP7.4
[46113](https://core.trac.wordpress.org/changeset/46113) - Comment out magic quote functions [in getID3 library]
[48046](https://core.trac.wordpress.org/ticket/48046) - Add array cast before count() in class-wp-xml-server.php (this is really for PHP 7.3)
[48041](https://core.trac.wordpress.org/ticket/48041)  - Add PHP info to travis output
[46149](https://core.trac.wordpress.org/changeset/46149) - Remove redundant PHP 4 code from do_action()

### CODE REVIEW

**Comment by bahiirwa** [comment]
As discussed on slack, the merge conflicts are still intact.

**Comment by nylen** [comment]
I see 46112 46113 and 46419 here. The other changesets (47783 48046 and 48041) are mentioned in the PR message but not included in the commits here?

**Comment by bahiirwa** [comment]
Thank you. I going to follow the changesets on https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/

**Comment by bahiirwa** [comment]
Thank you. I going to follow the changesets on https://make.wordpress.org/core/2019/10/11/wordpress-and-php-7-4/

In addition
[47783](https://core.trac.wordpress.org/ticket/47783) - phpmailer
[in getID3 library]
[48046](https://core.trac.wordpress.org/ticket/48046) - Add array cast before count() in class-wp-xml-server.php (this is really for PHP 7.3)
[48041](https://core.trac.wordpress.org/ticket/48041)  - Add PHP info to travis output

**Comment by bahiirwa** [comment]
If we are building for 7.4, shouldn't we add a 7.4 in our Travis build process? With at least a fail allowed for the start.

**Comment by nylen** [comment]
Yes, ideally Travis should be enabled and passing for PHP 7.4 in this same PR.

**Comment by bahiirwa** [comment]
- [x] Backported changes
- [x] Merge conflict fixes.
- [x] Travis build request for PHP added 7.4 .
- [x] CI builds requested.

**Comment by bahiirwa** [comment]
Test for 7.4 fails but I cannot figure out the issue since now we have some new test building slowly. I cannot rerun the build unfortunately.

**Comment by nylen** [comment]
The build should pass now. Here's what I saw that needed to be changed:

- Include another WP changeset, https://core.trac.wordpress.org/changeset/46155 (from https://core.trac.wordpress.org/ticket/47746).
- Update the importer plugin used in the unit tests, in particular to include https://github.com/WordPress/wordpress-importer/commit/00760596f40bf4ffe8496ed6786d806837073846 for PHP 7.4 compatibility. There is now a script to update this plugin again later, `bin/update-importer-plugin.sh`.
- Update Travis from Ubuntu 14.04 (ancient) to Ubuntu 16.04. This fixed some issues with required PHP modules not being loaded under PHP 7.4.

**Comment by nylen** [comment]
PHP 7.4 is passing, but PHP 5.6 with object cache is not: https://travis-ci.com/ClassicPress/ClassicPress/jobs/288593168

Let's try something else...

**Pull request merged**
