### PR TITLE
Change default_comment_status to closed

### PR DESCRIPTION
**Pull request by mattyrob**
***Originally Pull Request 793***
[Original Pull Request](https://github.com/ClassicPress/ClassicPress/pull/793) repository has been deleted.
Will need addition of a test for default setting once #1109 is merged.

## Description

This changes a setting that gets loaded into the database when CP initially installs, so that comments are turned **off** by default, not **on**.

## Motivation and context

The comment system is something that users should _choose_ to use, rather than have it forced on them and have to remember to disable it.

We no longer have Akismet as an included plugin, so we are currently enabling comments by default but not providing any way to deal with the mountains of spam this will generate. 

There is also the issue that comments can be enabled on media items by accident, even though the user is not even using posts or a blog. A user can therefore end up with thousands of images that are unintentionally made open to comments (and spam).

Full discussion is here: https://forums.classicpress.net/t/change-basic-settings-of-comment-options/2744

This has a lot of votes from the previous petition system (note there is also a duplicate petition).

## How has this been tested?

The change shown was made to one line in schema.php. A new CP instance was installed and it was noted that the box was now unticked.

### Before

before

### After

after

## Types of changes

New feature I guess (although I'd consider it more of a bug fix).

### CODE REVIEW

**Review by bahiirwa — APPROVED** [review]
## How was this tested?
- Installed new CP site.
- Checked the Discussions page. Autocomments are off.

## Screenshots

Pre-Commit

Screenshot 2022-09-15 at 13 35 27

Post Commit/Fix: Commenting on new articles disabled.

Screenshot 2022-09-15 at 13 33 44

**Review by xxsimoxx — APPROVED** [review]
### Test on a fresh installation
Looks good.

Settings -> Discussion
Schermata 2022-09-16 alle 08 22 21

On a new Post
Schermata 2022-09-16 alle 08 23 12

### Applying on an already installed site
No changes.
image

image

**Comment by bahiirwa** [comment]
@mattyrob Coding standards are failing on this.

**Comment by mattyrob** [comment]
@bahiirwa - Thanks, it was actually the precommit check that was failing as the tests were changing comment status for the QUnit tests. I had previously set comments to closed, but we should really still be testing against open comments so some changes were needed in the precommit generating code. Hopefully the most recent commit will work fully.

**Comment by mattyrob** [comment]
As per review comment on Slack - thanks @xxsimoxx

**Pull request merged**
