### PR TITLE
Add missing rel=noopener noreferrer to target=_blank

### LINKED ISSUE #537: Missing rel="noopener noreferrer" to any target="_blank"
I submitted #532 to WP to make some comparison notes and realized they have another implementation going on i.e. https://core.trac.wordpress.org/ticket/37941.

As I feared there are more files with this issue and the patches pick it out. How do we proceed with this? Do we make minor patches to CP because this has lagged with WP for over 2-3 years.

### PR DESCRIPTION
**Pull request by bahiirwa**
This PR seeks to close #537 as a follow up to #532 (Doing the same job.)

Only one piece of the code from [Ticket #37941](https://core.trac.wordpress.org/ticket/37941) still is not introduced. I am suggesting a different PR for it. 

It has to do with [Ticket #37941: 37941.2.diff](https://core.trac.wordpress.org/attachment/ticket/37941/37941.2.diff) that solves the missing rel=noopener noreferrer to target=_blank for the Admin Bar.

### CODE REVIEW

**Comment by nylen** [comment]
Seems like there is still a function that generates links (on the plugin screen?) which needs to be updated so that Travis will pass.

Some of these links already have `rel="noopener"` but after reading a bit I think it is probably a good idea to add `noreferrer` also, for IE11/Edge support. Here are some resources I found on this:

- https://mathiasbynens.github.io/rel-noopener/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types#Browser_compatibility
- https://caniuse.com/#feat=rel-noopener

**Comment by bahiirwa** [comment]
> It has to do with [Ticket #37941: 37941.2.diff](https://core.trac.wordpress.org/attachment/ticket/37941/37941.2.diff) that solves the missing rel=noopener noreferrer to target=_blank for the Admin Bar.

This is the missing function. I have updated that in latest commit.

**Comment by bahiirwa** [comment]
Would love to work on this again. How do I request a new travis rebuild on this?

**Comment by bahiirwa** [comment]
Awaiting the feedback/decision on https://forums.classicpress.net/t/classicpress-browser-support/815/7 to fix this the best way possible.

**Comment by mattyrob** [comment]
Large number of conflicts here, agree that we close.

**Pull request closed without merging**
