### PR TITLE
PHP Compatibility fixes

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
PHP Compatibility fixes over several core files
Mainly external libraries left and 2 core feels that require further investigation
PHPUnit tests are still all passing locally

## Motivation and context
GitHub Actions contains PHP compatibility tests, they are currently allowed to fail without impacting on further testing. This PR is a start in fixing many of these issues so that the automated testing can be fully enabled.

## How has this been tested?
PHP Unit Tests are still passing locally

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by mattyrob** [comment]
As it now stands I believe there are errors or warning remaining in the following files:

src/wp-includes/class-simplepie.php
src/wp-includes/SimplePie/File.php
src/wp-includes/SimplePie/Item.php
src/wp-includes/class-phpmailer.php
src/wp-includes/class-snoopy.php

The majority if these may well get address with the existing PRs that update PHPMailer and SimplePie.

**Comment by mattyrob** [comment]
Upstream tickets for reference if we want to consider backporting:
https://core.trac.wordpress.org/ticket/49810
https://core.trac.wordpress.org/ticket/49922

**Comment by nylen** [comment]
Still left to do on this: do this PR as a backport of relevant WP changesets instead, and then compare to what's in this branch now.

**Comment by mattyrob** [comment]
Closing in favour of:
https://github.com/ClassicPress/ClassicPress/pull/958

**Pull request closed without merging**
