### PR TITLE
Backport of WordPress Ticket 8973

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
See upstream ticket:
https://core.trac.wordpress.org/ticket/8973

## Motivation and context
Fixes an old bug in comment counts

## How has this been tested?
Unit tests are included from upstream patch

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by bahiirwa** [comment]
Travis is breaking because of the merge conflicts. @mattyrob are you in position to resolve those?

**Comment by mattyrob** [comment]
I've just pushed an update to address the mega conflicts.

**Comment by bahiirwa** [comment]
Fixes look good.

**Comment by nylen** [comment]
> dd6337e WP-r48113: Posts, Post Types: Simplify `test_setup_postdata_loop()`

Looking at https://core.trac.wordpress.org/ticket/8973, this commit should probably be `48133` instead of `48113`?

> 9fd5579 On branch backport/8973

What is this commit?

**Comment by mattyrob** [comment]
> What is this commit?

Ah, this would be an embarrassing error on my part - whoops. I'll close off this PR and start again.

**Pull request closed without merging**
