### PR TITLE
Update class-wp-query.php

### PR DESCRIPTION
**Pull request by KTS915**
See https://github.com/ClassicPress/ClassicPress/issues/687

### CODE REVIEW

**Comment by nylen** [comment]
Is this PR based on a WP changeset? If so, the instructions here should be followed to include it in ClassicPress: https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress

Other things that are good to include in PRs like this:

- Links to relevant WP tickets and changesets
- Description of the error this PR prevents, and under what circumstances it may occur (how to see the error on a test install with PHP 8)

**Comment by bahiirwa** [comment]
@nylen Unfortunately, we haven't seen this change upstream.
Ref: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-query.php#L765

It is an issue @KTS915 has experienced in CP. I would have loved more informationon how to replicate it

**Comment by KTS915** [comment]
Am surprised you haven't experienced it when trying CP with PHP8, because it happened immediately to me, as someone else has explained here: https://kagg.eu/en/why-wordpress-5-5-3-with-php-8-shows-404-on-every-page/

**Comment by bahiirwa** [comment]
~~> @nylen Unfortunately, we haven't seen this change upstream.~~
> Ref: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-query.php#L765

My bad. Scratch that. :-(

I can confirm from trac blame. [Changeset 48960](https://core.trac.wordpress.org/changeset/48960) from [issue](https://core.trac.wordpress.org/ticket/50913)

We need a backport of this.

**Comment by bahiirwa** [comment]
I have tested it on the front-end following the shared read. Here are my results

## How to replicate:
- Install CP on PHP 8.0 server
- Visit front end of your site.

Patch works as mentioned with backport

##Before patch
Screenshot 2021-07-21 at 07 35 17

## After patch
Screenshot 2021-07-21 at 07 35 26

**Review by bahiirwa — APPROVED** [review]

**Review by mattyrob — APPROVED** [review]

**Review by nylen — APPROVED** [review]
Looks good, thanks. Committers: please add a better commit message when merging.

**Comment by mattyrob** [comment]
Approved at Slack meeting.

**Pull request merged**
