### PR TITLE
Deprecate scripts and styles

### PR DESCRIPTION
**Pull request by KTS915**
This PR lists scripts and styles that are deprecated in CP v2.1, together with a few that were previously deprecated in WP without any apparent notices other than in notes within the code.

### CODE REVIEW

**Comment by KTS915** [comment]
I have set the milestone as v2.2 because there are strings here that will need to be translated.

It's also worth noting that this PR addresses Issues #1291, #1413, and #1415.

**Comment by KTS915** [comment]
> If a plugin register it's own copy of a deprecated script this should not trigger the deprecation.
> 
> Scenario:
> 
> ```
> wp_deregister_script('farbtastic');
> wp_enqueue_script('farbtastic', plugins_url('js/farbtastic.js', __FILE__), ['jquery'], false, true);
> ```
> 
> The way I've found to solve this is this code (but maybe some better solution can be found):
> 
> ```
> global $wp_scripts;
> if ( wp_script_is( $deprecated_script, 'enqueued' ) && ! str_starts_with( $wp_scripts->registered[$deprecated_script]->src, plugin_dir_url('') ) ) {
> ```

But surely a developer shouldn't use the same handle? They can load their own script but using a different handle.

**Comment by ginsterbusch** [comment]
> 
> But surely a developer shouldn't use the same handle? They can load their own script but using a different handle.

reality vs. wishful thinking.

how often I've found a direct "wp_dequeue_script('juery'); wp_enqueue_script( 'jquery', ..'" is next to uncountable.

So, no, that happens ALL. THE. TIME.
Just always think of the worst case scenario. Esp. with anything WP.

**Comment by KTS915** [comment]
>reality vs. wishful thinking.

>how often I've found a direct "wp_dequeue_script('juery'); wp_enqueue_script( 'jquery', ..'" is next to uncountable.

>So, no, that happens ALL. THE. TIME.

But isn't that a good reason to use the handles here? If, for example, two developers both attempt to use the same handle, there's going to be a problem. By deprecating the use of the handle, we actually encourage devs to use their own handles, as they should.

**Comment by KTS915** [comment]
> `_cp_deprecate_wp_enqueue_scripts`, `_cp_deprecate_login_enqueue_scripts` and `_cp_deprecate_admin_enqueue_scripts` have the same code. Why not to hook the same function?

Yes, of course you're right. These functions started out with different code but eventually they ended up the same. I will get that done!

**Comment by xxsimoxx** [comment]
I see deprecations triggered by core, all about `thickbox`, in Dashboard, Edit Post, Themes and Import.
If confirmed, can be addressed in another PR?

**Comment by xxsimoxx** [comment]
Added some simple unit tests.

**Comment by KTS915** [comment]
> I see deprecations triggered by core, all about `thickbox`, in Dashboard, Edit Post, Themes and Import. If confirmed, can be addressed in another PR?

It might be that a script dependency hasn't been updated. Which version of CP did you check with?

**Comment by xxsimoxx** [comment]
Your `KTS915:deprecate-scripts-and-styles` branch.

**Comment by xxsimoxx** [comment]
Seems that removing `add_thickbox()` from the following files works well :
- `src/wp-admin/edit-form-advanced.php`
- `src/wp-admin/import.php`
- `src/wp-admin/index.php`
- `src/wp-admin/themes.php`
- `src/wp-admin/update-core.php`

Other files I haven't tested:
- src/wp-admin/network/index.php
- src/wp-admin/network/themes.php
- src/wp-admin/network/site-themes.php
- src/wp-includes/class-wp-editor.php
- src/wp-includes/general-template.php

**Comment by KTS915** [comment]
Removing the call the function in those files should work too. Thickbox isn't used anywhere in core in the nightlies or v2.1.

**Review by xxsimoxx — APPROVED** [review]

**Pull request merged**
