### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
GitHub provides the functionality via 'Action' to run testing locally without reliance on other providers, for example Travis. As discussed on Slack, Travis have had issues reported and are not as robust in support open source now.

## Motivation and context
This PR runs PHPUnit tests, Javascript QUnit tests, Javascript and PHP Code sniffs and PHPCompatibility checks using GitHub Actions.
PHPUnit tests have required some minor amendment to some Unit Tests as well as a small addition to core image handling code. All tests operated and are passing with some skipped tests perhaps worth a review or a revisit.
The Javascript unit tests and code sniffs pass.
PHP Code sniffs and Compatibility checks are currently allowed to fail - there are many changes needed in the core code before these tests can be fully implemented.

## How has this been tested?
This PR is designed to be functional on the develop branch of the base repository but with some minor adjustments in another fork of the code, these tests are self checking.
https://github.com/mattyrob/ClassicPress/tree/github-actions-test

This could be adopted and run in parallel with Travis testing until we are fully satisfied that this fully reproduced the Travis checks.

### Before
Screenshot 2021-02-01 at 18 50 37

### After
Screenshot 2021-02-01 at 18 49 44

## Types of changes
- New feature

### CODE REVIEW

**Comment by nylen** [comment]
Excellent work, thank you @mattyrob and @timbocode ! This migration is a big task and this is a great start at it.

I am making a few changes (not finished yet):

- It's better to backport individual changes from WP rather than copy/pasting whole files, this way we can track what has been changed and (to some extent) why.
- There are some additional checks run by `grunt precommit:verify` that should also be executed.
- Restoring the run with memcached.

The last few commits have probably broken at least a couple of things... I will fix them, then make a few commits that I would expect to fail in different ways and verify that they do indeed fail, and then this should be good to go.

**Comment by mattyrob** [comment]
@nylen 

Thanks for taking this forward. It looks like things have progressed even further and very quickly.

The Precommit tests seems to need a specific version of PHP, I think the default PHP version is 8.0.1 so it may need to be setup to a lower version for this task.

Also the JavaScript code sniffer tests seem to have been lost - was that intentional?

**Comment by timbocode** [comment]
Node v10 reaches eol on 2021-04-30. Would we be better using v12 or perhaps even v14?

WordPress have `lts/*` in their .nvmrc. v14 is the active LTS.

**Comment by nylen** [comment]
@mattyrob:

> The Precommit tests seems to need a specific version of PHP, I think the default PHP version is 8.0.1 so it may need to be setup to a lower version for this task.

Yes, that needs to be re-worked a bit, PHP probably needs to be installed like it is for the PHPUnit tests because `grunt precommit` also runs about two PHPUnit tests. This could be set up as only one job that runs both coding standards and the pre-commit checks, so that the initialization for those two steps is shared.

> Also the JavaScript code sniffer tests seem to have been lost - was that intentional?

They should be running as part of `grunt precommit`, but that needs to be confirmed (by introducing a coding error and verifying that it fails appropriately). This can also be made clearer.

@timbocode:

> Would we be better using [Node] v12 or perhaps even v14?

Probably, but let's handle that in a separate PR where we upgrade it for the whole build process.

> WordPress have `lts/*` in their .nvmrc. v14 is the active LTS.

I think it's better to peg this to a specific version because upgrades could change the results of the build/test processes. Should be unlikely to happen with just a node upgrade, but still possible.

**Comment by mattyrob** [comment]
The two failing tests are now working and passing with PHP version specified for the recommit check and memcache server now operational on the PHPUnit tests.

I've been pondering on these points now:
1/ Do we need the document block detailing the steps when the step descriptions are in place and summarise well each step? (We could remove them or if we keep them they probably need checking and updating).
2/ Do the file names and overarching test names perhaps need updating to reflect what each test is actually doing now?

**Comment by timbocode** [comment]
1. Personally, I think the comment block provides a useful summary of the file's content and purpose so I'd probably be inclined to leave it in.
2. This is worth looking at. Do you have any suggestions?

**Comment by mattyrob** [comment]
@timbocode 

1/ Fair enough, was just a thought.

2/ File name changes:
javascript-tests.yml > qunit-tests.yml
coding-standards.yml > precommit-and-coding-standards.yml

And I wonder if switching the 2 jobs around in the latter file makes sense too.

**Comment by timbocode** [comment]
> 2/ File name changes:
> javascript-tests.yml > qunit-tests.yml

How about `javascript-tests.yml` > `javascript-qunit-tests.yml`?

> coding-standards.yml > precommit-and-coding-standards.yml

Looks fine to me.
> 
> And I wonder if switching the 2 jobs around in the latter file makes sense too.

Yep, that does make sense (to me at least). However, I also wondered if they should be in separate files altogether. Is there any advantage to them being in the same file?

**Comment by mattyrob** [comment]
> > 2/ File name changes:
> > javascript-tests.yml > qunit-tests.yml
> 
> How about `javascript-tests.yml` > `javascript-qunit-tests.yml`?

Yes, that's better again.

> Yep, that does make sense (to me at least). However, I also wondered if they should be in separate files altogether. Is there any advantage to them being in the same file?

No advantage, unless the steps rely on each other and need to be done in that order. In fact, if they are not reliant on each other, splitting may provide an overall speed advantage.

**Comment by timbocode** [comment]
I personally think they'd be better in separate files but I think we need James's view. Ping @nylen.

**Comment by nylen** [comment]
I don't really have a preference. I put the precommit check in there where it was for a couple of reasons, not necessarily good ones:

- I was thinking that it might be better to run less overall jobs at once, and since phpunit takes the longest then other, shorter jobs can be combined together and (phpunit) can run in parallel with the combination of (precommit + coding standards). I don't feel like I understand GitHub Actions and how it structures its workflows / job steps well enough to know whether this is really correct or makes sense though.
- I saw that the coding standards job already had some of the needed setup in place and put the precommit checks in there just to get it working quickly.

**Comment by timbocode** [comment]
Given that this is fairly new to us all, perhaps we should just leave things as they are for now and keep our eye on things. We can make further changes as we see fit at any time.

If everyone is happy with this, we can probably go ahead and merge this.

Thoughts anyone?

**Comment by mattyrob** [comment]
> Given that this is fairly new to us all, perhaps we should just leave things as they are for now and keep our eye on things. We can make further changes as we see fit at any time.
> 
> If everyone is happy with this, we can probably go ahead and merge this.
> 
> Thoughts anyone?

I have no reservations to merging this as it stands, all of my previous comments are just semantics and can be sorted in time.

**Review by nylen — APPROVED** [review]
Looks like everything is running properly. Thanks again for pushing this forward!

**Comment by bahiirwa** [comment]
Thanks for getting this to work. 

Question: How do we refresh the PRs that exist to run the test?

**Comment by timbocode** [comment]
> How do we refresh the PRs that exist to run the test?

See #661. Hoping that will resolve this. Failing that, I'd suggest pushing an empty commit.

**Comment by nylen** [comment]
To update existing PRs so that they run GitHub Actions, you need to merge the PR branch with `develop`.

The general steps are as follows:

- check out your PR branch
- `git fetch upstream` (depends on the name you've given to the https://github.com/ClassicPress/ClassicPress remote repository, this should usually be `upstream`)
- `git merge upstream/develop` (same)
- `git push` (this should usually be configured to push to the same branch as your PR once you have checked out that branch)

I just tried this with #649 and nothing else was required.

See also https://github.com/ClassicPress/ClassicPress/pull/661#issuecomment-779241707

**Pull request merged**
