### PR TITLE
Fix PHP notice and unexpected behavior when editing a post with an invalid author

### LINKED ISSUE #564: PHP notice when editing a post with an invalid author
When editing a post with a `post_author` value that points to a non-existent user, there are some PHP notices:

```
PHP Notice: Trying to get property 'display_name' of non-object in .../wp-includes/user.php on line 1128
PHP Notice: Trying to get property 'user_login' of non-object in .../wp-includes/user.php on line 1128
PHP Notice: Trying to get property 'ID' of non-object in .../wp-includes/user.php on line 1135
PHP Notice: Trying to get property 'ID' of non-object in .../wp-includes/user.php on line 1136
```

In the following code path, `get_userdata` will return `false` and this value will be included as part of the `$users` array, then looped over and accessed as if it were a user object:

https://github.com/ClassicPress/ClassicPress/blob/f765dbfa00cf74fd51cae45ffb13cd2536417e4b/src/wp-includes/user.php#L1118-L1135

Suggested fixes:

- Add a new entry to the `$users` array, which preserves the current user ID but indicates to the user that this post has an invalid author set.
- Just fix the notice, and preserve the current behavior where the post author will be reset to the current user when it is saved.

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Potential fix for #564, updated to fix the issue as described in the original report:
>Add a new entry to the `$users` array, which preserves the current user ID but indicates to the user that this post has an invalid author set.

## Motivation and context
Fix for an open issue. Fixes #564

## How has this been tested?
Needs testing (manual testing with screenshots, and automated tests)

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by nylen** [comment]
Hi @mattyrob, after looking at this again I think it would be better to keep the invalid user ID but indicate that the current author is invalid. Something like this (untested):

```diff
diff --git a/src/wp-includes/user.php b/src/wp-includes/user.php
index f0e4c21c46..1e3461e5c1 100644
--- a/src/wp-includes/user.php
+++ b/src/wp-includes/user.php
@@ -1116,12 +1116,24 @@ function wp_dropdown_users( $args = '' ) {
 			}
 
 			if ( ! $found_selected ) {
-				$users[] = get_userdata( $r['selected'] );
+				$selected_user = get_userdata( $r['selected'] );
+				if ( $selected_user ) {
+					$users[] = $selected_user;
+				} else {
+					// The selected user ID was not found as a valid user.
+					$users[] = (object) array(
+						'_invalid' => true,
+						'ID'       => $r['selected'],
+					);
+				}
 			}
 		}
 
 		foreach ( (array) $users as $user ) {
-			if ( 'display_name_with_login' === $show ) {
+			if ( ! empty( $user->_invalid ) ) {
+				/* translators: user ID */
+				$display = sprintf( __( '(Invalid user: ID=%d)' ), $user->ID );
+			} elseif ( 'display_name_with_login' === $show ) {
 				/* translators: 1: display name, 2: user_login */
 				$display = sprintf( _x( '%1$s (%2$s)', 'user dropdown' ), $user->display_name, $user->user_login );
 			} elseif ( ! empty( $user->$show ) ) {
```

This would also need a unit test (this function already has some tests). Shall I push this code here, or as a new PR?

Also, in the future it's helpful to know more details about what steps have been followed to test a code change, and what the result of the testing was. For example: _Post with invalid author shows up as "X" in the author dropdown, upon saving, author is now user id "Y"_

**Comment by mattyrob** [comment]
@nylen 

Feel free to push the updated approach here, saves creating another PR,

**Comment by mattyrob** [comment]
That's a better patch than mine - gives a better user experience rather than silently failing.

**Comment by nylen** [comment]
Merging, this is working as intended:

### Before

pr 572 before

### After

pr 572 after

**Pull request merged**
