### PR TITLE
Rebuild Text (TinyMCE) widget based on PHP instead of `backbone.js`

### PR DESCRIPTION
**Pull request by KTS915**
This PR follows a similar pattern to PR #1628 in that it is about rebuilding a core widget so that it is based on PHP instead of a `backbone.js` template. This significantly reduces the amount of JavaScript used, which makes it render faster as well as being much easier to maintain.

In this case, it also paves the way for the widget to be modified by a future PR so that it works with the new Media Library grid view when adding media to the widget.

After experiencing some gotchas with PR #1628 (all of which I think I have now resolved), I have tested this on two different sites and it seems to work both on `widgets.php` and the Customizer.

### CODE REVIEW

**Comment by xxsimoxx** [comment]
Getting weird duplication in Chrome:

image

**Comment by KTS915** [comment]
I was hoping I'd managed to prevent that, @xxsimoxx ! Could you try applying #1628 at the same time? I'm wondering whether it's some code in the pre-modded Custom HTML widget that's causing this (and I re-built that widget before I re-built this one).

**Comment by xxsimoxx** [comment]
Merging #1628 into this branch solves the issue.

**Comment by mattyrob** [comment]
Seeing duplication of content with this PR, and also when newly placing the Widget it seems that the TinyMCE editor is not initialised and is not usable until the page is reloaded, but then the Text tab in the editor pane doesn't work.
Screenshot 2024-11-06 at 16 30 19

**Comment by mattyrob** [comment]
This PR was merged into #1628 and merged as a single PR

**Pull request closed without merging**
