### PR TITLE
Default filters WP Plugins by "classicpress" keyword

### PR DESCRIPTION
**Pull request by smileBeda**
[Changed] Link to `/plugins.php` (Add WP Plugin) now leads to a default filtered list of Plugins tagged with `classicpress`.

## Description
Added the `?s=classicpress&tab=search&type=tag` query string to the `Add WP Plugin` menu and the `Add WP Plugin` button on `Installed Plugins` screen.
This ensures that whenever a user clicks on the menu or button, they see at first _compatible, installable_ plugins, and not a avalanche of "red" plugins that say `This plugin doesn’t support ClassicPress.`
There's no point in showing those plugins at all.
The user can still find them by running a either empty, or not empty search.

## Motivation and context
Several times (such as [here](https://forums.classicpress.net/t/classicpress-quickly-becoming-obsolete-lets-fix-that/3963)) it has been complained that if you look for a plugin in the Add WP Plugin screen, (too) many appear not installable.

While this may or may not be true - the truth is, if someone opens that screen on CP, it is really rather a "why am I looking at this" than a "aha. there are plugins!"

Of course, this solves not much, but it solves the "first impression" being "red/do not go"
In terms of impressions, this is definitely better than 100eds of non-installable plugins in a list.

## How has this been tested?
Locally tested by clicking on the menu/button.

### Before
Screenshot 2022-07-03 at 12 29 35

### After
Screenshot 2022-07-03 at 12 30 08

## Types of changes
- Changed feature

### CODE REVIEW

**Review by bahiirwa — APPROVED** [review]
Minor change non breaking. It helps with userbility and perceptions. Big plus

**Comment by joyously** [comment]
Instead of searching for a tag (today shows 18), search for keyword (today shows 92).

**Comment by smileBeda** [comment]
Agreed, results are shuffled a bit differently, however the numbers speak for themselves.
We got 3 "does not work with" in the 92 plugins, but that is still better than pages of "does not work with".

Whether or not those plugins then actually do work with CP is another question (not even the _tag_ can guarantee us that, so that's OK too)

**Comment by viktorix** [comment]
>Most of the resulting plugins - even if appearing in the search results, have nothing at all to do with CP
Neither their tags nor content actually feature the word classicpress at all.
Why might that be?

Some search algorithms will split a word, like "Classic" and "Press". I don't know if this is the case here, but I did notice this when searching for ClassicPress in various places.

**Comment by viktorix** [comment]
Tested this PR, works great. No issues found. 
image

**Comment by viktorix** [comment]
@smileBeda did you notice a few plugins show up in search results that do not mention ClassicPress and are incompatible? It goes back to my previous comment about ClassicPress being split "Classic" and "Press". I don't know if there's any way to filter them. I know it's possible to use JS to remove them, but that's a bit hacky.

image

Displaying ClassicPress compatible plugins is still better than the popular tab. So this shouldn't disqualify this PR from being merged.

**Comment by smileBeda** [comment]
> We got 3 "does not work with" in the 92 plugins, but that is still better than pages of "does not work with".

Yes, as mentioned in my [previous reply](https://github.com/ClassicPress/ClassicPress/pull/1031#issuecomment-1173094937).
That was not the case when searching for the actual _tag_ as I did initially but then, we get only 18 results versus 92 

There is no way to filter them, because the filter is basically either keyword, tag or author
Hiding them with any "hardcoded" approach isn't a good idea because A) the results will still show 92 found but actually display less and more importantly, it might just add another non-compatible plugin tomorrow and we'd have to add to our JS or CSS to hide that
I think this is as good it gets for an _interim_ solution stopping the image from getting hurt.

It is also why I think adding the Dir Integration (plugin) as another interim solution (until full dir integration) can additionally help. The plugin would have to be added as either a "hint" (to install) or even as a bundled plugin in new installs (and if possible, in updates)
This would then allow to smoothly remove the plugin once real dir integration is done, without any semver disruption. But that is topic for another ticket.

**Review by xxsimoxx — APPROVED** [review]
Tried _after fixing merge conflicts_, looks good.

**Pull request merged**
