### PR TITLE
Login and Registration: Add a "Show password" button

### PR DESCRIPTION
**Pull request by mattyrob**
The ability for users to see the password they're typing improves usability and accessibility of the login users flow.

- brings the login screen in line with the same feature already used in the New User, Edit User, and Reset Password pages
- improves association of labels and input fields by using explicit association with `for` / `id` attributes
- slightly increases the "Remember me" label font size

WP:Props johnbillion, Iceable, audrasjb, joyously, adamsilverstein, boemedia, DrewAPicture, shadyvb, birgire, peterwilsoncc, pento, anevins, davidbaumwald, whyisjake, afercia.
Fixes https://core.trac.wordpress.org/ticket/42888.

Conflicts:
  src/wp-admin/css/forms.css
  src/wp-admin/css/login.css
  src/wp-admin/js/user-profile.js
  src/wp-login.php
----
Merges https://core.trac.wordpress.org/changeset/46256 / WordPress/wordpress-develop@0ff03b3290 to ClassicPress.

## Description
As per suggestion on Slack to backport a WP change

## Motivation and context
Adds a 'Show Password' button in the password field on the login page.

## How has this been tested?
User testing

## Types of changes
- New feature

### CODE REVIEW

**Comment by nylen** [comment]
I'd like to test this a bit before merging it, but the backport itself looks good on this one. Thanks!

We'll also need to catch up with the "post-commit" discussion starting in https://core.trac.wordpress.org/ticket/42888#comment:62 and include the other relevant changesets.

**Comment by striebwj** [comment]
From my quick test I think the button needs a bit of tweaking: 
Screen Shot 2019-12-06 at 3 00 20 PM

**Comment by nylen** [comment]
> From my quick test I think the button needs a bit of tweaking:

This probably has to do with some of the related WP changesets that have yet to be merged.

Let's not forget that WP also has an "admin styles refactoring" going on pretty much across the board: https://make.wordpress.org/core/2019/10/18/noteworthy-admin-css-changes-in-wordpress-5-3/

As a result of this, we'll need to be careful with how we merge in subsequent changesets - there will probably be parts of some commits that we will need to modify or leave out.

**Comment by striebwj** [comment]
I tweaked the padding. The dashicon is centered, and the button fits inside the input box now.

Updated screenshot:
Screen Shot 2019-12-12 at 6 40 24 PM

**Comment by nylen** [comment]
Ok, here is what I think still needs to be done in order to land this:

- Backport https://core.trac.wordpress.org/changeset/46334
- Backport https://core.trac.wordpress.org/changeset/46371 (probably only part of it, since this is part of the larger "admin styles refactoring" I mentioned above)
- Backport https://core.trac.wordpress.org/changeset/46372
- Test on supported browsers, especially IE11 and Edge since we know from the WP discussion that they will have issues with the current version
- Look through https://core.trac.wordpress.org/ticket/42888, https://make.wordpress.org/core/2019/10/18/noteworthy-admin-css-changes-in-wordpress-5-3/, other commits, and any other resources to make sure we didn't miss anything with this change
- Release a beta or RC version and call for testing

**Comment by nylen** [comment]
I am inclined to close this. Backporting any change that intersects with WP's refactoring of admin styles is especially complicated (see above for some changesets that still need to be included, and there may be more since then). Also, this improvement hasn't been requested since this PR was made. Thoughts?

**Comment by mattyrob** [comment]
Is there an Accessibility argument to including this in some form? Perhaps we should investigate creating our own solution rather than back porting if the admin area code gets impacted.

**Comment by mattyrob** [comment]
@nylen I've been looking at making a CP level change to introduce this and managed it with a pretty simple plugin.

Can I propose that we push this back to a future release for now and investigate this feature more as a plugin before further consideration of making this part of core.

**Comment by nylen** [comment]
@mattyrob sounds good, I will close this then.

**Pull request closed without merging**
