### PR TITLE
Update importer API

### LINKED ISSUE #1168: 💡Replace api.wordpress.org/core/importers/1.1 endpoint
### Context

ClassicPress makes calls to `api.wordpress.org/core/importers/1.1` in `/wp-admin/includes/import.php` to get a list of importer plugins. WordPress API endpoint should be replaced with a ClassicPress API endpoint.

This could be considered a privacy issue.

### Possible implemantion

PR has been submitted to create a new API endpoint:
https://github.com/ClassicPress/ClassicPress-APIs/pull/59

### Possible Solution

Once the new API endpoint has been merged and taken live, replace URL in the core:
`/wp-admin/includes/import.php`.

### Will you be able to help with the implementation?

Yes, API endpoint PR has been submitted.

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Replace the hard-coded API URL used for collecting a list of importer plugins.

## Motivation and context
Fixes #1168 however it should be noted that the Wordpress importer can no be installed due to the plugin declaring it is incompatible.
It also seems that the default list contained in the `` file is in use prior to this PR so maybe the WordPress API is failing.

## How has this been tested?
Local testing and viewing of database transient entry.

### Before
Screenshot 2022-11-17 at 11 55 01

### After
Screenshot 2022-11-17 at 11 55 11

## Types of changes
- New feature

### CODE REVIEW

**Comment by viktorix** [comment]
> Fixes https://github.com/ClassicPress/ClassicPress/issues/1168 however it should be noted that the Wordpress importer can no be installed due to the plugin declaring it is incompatible.

This will most likely get replaced by ClassicPress Importer. Should we note WordPress Importer doesn't work? It actually works, just needs to be installed manually.

**Comment by bahiirwa** [comment]
Good for merge.

**Review by bahiirwa — APPROVED** [review]
LGTM for merge as discussed on slack

**Review by xxsimoxx — APPROVED** [review]
LGTM.

**Comment by mattyrob** [comment]
API endpoint is updated to remove reference to the currently broken WordPress Importer.

This PR is updated with a message for end users that links to a document describing the steps that is in progress.

**Review by bahiirwa — APPROVED** [review]
LGTM

**Comment by mattyrob** [comment]
PR has two reviews.

**Pull request merged**
