### PR TITLE
WP-r50677: Login and Registration: Check if `$_GET['login']` is set before using it in `wp-login.php`

### PR DESCRIPTION
**Pull request by KTS915**
Login and Registration: Check if `$_GET['login']` is set before using it in `wp-login.php`.

This avoids an "Undefined index" PHP notice displayed as part of password reset process if `$_GET['key']` is set, but `$_GET['login']` is not.

WP:Props satrancali.
Fixes https://core.trac.wordpress.org/ticket/52980.

Conflicts:
- src/wp-login.php

---

Merges https://core.trac.wordpress.org/changeset/50677 / WordPress/wordpress-develop@924343c8fc to ClassicPress.

### CODE REVIEW

**Review by nylen — CHANGES_REQUESTED** [review]
From https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#tips-for-good-prs :

> It is always a good idea to look at the "Files" view on GitHub after submitting your PR to verify that the changes look as expected. [...] If you see something that looks out of place, you can make an edit to fix it and push a new commit to your PR.

The [Files view](https://github.com/ClassicPress/ClassicPress/pull/800/files) for this PR looks very different than "expected" (which is basically that the same change from https://core.trac.wordpress.org/changeset/50677 should be applied). In this case it looks like the reason is that WP has reformatted `wp-login.php` and CP hasn't, and `git` doesn't deal with this situation well.

Since this is a one-line change, the best thing to do is add (a) new commit(s) to this PR to back out the current changes and manually edit the line that says `if ( isset( $_GET['key'] ) ) {` as in the WP changeset.

**Comment by KTS915** [comment]
Interesting. On my local install, that's what I did. So I presumed it would copy over. Will do as you say!

**Comment by KTS915** [comment]
Looks like it worked this time! Sorry about the first try!

**Comment by KTS915** [comment]
The change requested was done. Can we get this approved now and ready to go, please? It's a very small change.

**Review by mattyrob — APPROVED** [review]

**Review by bahiirwa — APPROVED** [review]

**Comment by mattyrob** [comment]
@KTS915 - could you check the conflicts on this PR please?

**Comment by KTS915** [comment]
@mattyrob, I would if I could, but I have no idea what I'm looking at. It's really a very simple change, so I'm guessing that the conflict is simply because CP has been updated since I submitted this and the relevant line has now changed. But I can't work out what I'm supposed to do either visually or by following those command line instructions.

All that's involved here is changing
`if ( isset( $_GET['key'] ) ) {`
to `if ( isset( $_GET['key'] ) && isset( $_GET['login'] ) ) {`

**Comment by mattyrob** [comment]
Simple fix, cannot merge due to conflicts.

Following command line prompts to merge this to core.

**Comment by bahiirwa** [comment]
@mattyrob you should be able to make pushes to the branch as a manager of the repo.

**Comment by mattyrob** [comment]
@bahiirwa I can checkout out the PR but as the remote branch is deleted it seems to be read only.

I followed the commands on here that details downloading and applying the changes as a patch and merged directly into `develop`.

**Comment by mattyrob** [comment]
[Merged](https://github.com/ClassicPress/ClassicPress/commit/88d2821246b80af225ea16ccf38d3fc6e49dc595)

**Comment by bahiirwa** [comment]
Could be Tim did not allow for maintainers to make pushes on creating PR.

@KTS915 you could 

Locally:
- delete this branch
- checkout of an updated develop branch into this same branch name
- make the changes desired 
- force push to the same branch
- The PR will self update with new stuff. And will be good for merge.

**Pull request closed without merging**
