### PR TITLE
If updating a plugin, ensure the minimum PHP version requirements are satisfied.

### PR DESCRIPTION
**Pull request by marodok**
Compatibility update (with WordPress), need to be tested for issue #387

## Description

Added code from WP, wp-admin/includes/class-wp-automatic-updater.php

// If updating a plugin, ensure the minimum PHP version requirements are satisfied.
if ( 'plugin' === $type ) {
	if ( ! empty( $item->requires_php ) && version_compare( phpversion(), $item->requires_php, '<' ) ) {
		return false;
	}
}

## Motivation and context
When plugins are distributed, they use a the minimum PHP version. This will prevent the autoupdate install a plugin if the server has not the required PHP version. Also keeps compatibility with WP.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Mte90** [comment]
I confirm that the code is the same of https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-automatic-updater.php#L210
The commit is https://github.com/WordPress/WordPress/commit/8d04086af3473df096b9c5b24423c839b894e480#diff-eda7a45ac51a61594800209b35ee7e20
I am wondering if we are missing any other changeset about like notice the user about the wrong php version:

- https://core.trac.wordpress.org/changeset/44937
- https://core.trac.wordpress.org/changeset/44939

So I think that is pr is incomplete.

**Comment by marodok** [comment]
Thank you for the review @Mte90 , i just added the missing code parts.

Please check it out and let me know if there is any change pending.

**Comment by nylen** [comment]
@marodok ?

**Comment by nylen** [comment]
Closing due to inactivity.

**Pull request closed without merging**
