### PR TITLE
WP-r50256: Media: Pause any playing media when closing the the media …

### PR DESCRIPTION
**Pull request by mattyrob**
…modal.

Previously, any video or audio playing in the media modal failed to stop playing when the modal was closed. Now we pause the player when the modal is closed.

WP:Props adamsilverstein, hellofromTonya, paaljoachim, Mista-Flo, Clorith, justinahinon, afercia, amolv.
Fixes https://core.trac.wordpress.org/ticket/48562.

---

Merges https://core.trac.wordpress.org/changeset/50256 / WordPress/wordpress-develop@de258c87e6 to ClassicPress.

## Description
As highlighted on Slack, this is a bug that affects ClassicPress too. Any audio or video playing in a modal box in admin will continue playing if the modal box is closed.

## Motivation and context
This bug creates strange and annoying behaviour in the admin area when testing media file content. The fix provides a better user experience and is more intuitive.

## How has this been tested?
In the upstream patch several users report successful user testing and there are links to videos showing before and after effects off the bug and the fix.

## Screenshots
See above.

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by mattyrob** [comment]
@nylen 

I have synced this PR with upstream `develop` changes but there is an error in the testing.

`grunt recommit` needs to be run and committed however I get an error performing this locally as follows:
`Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)`

Can you offer a suggestion to fix this locally or will you need to run the `grunt recommit`?

**Comment by mattyrob** [comment]
I have tested this now that I have unit tests all passing.

To confirm, the patch use the following steps.

1. Go to Media > Library
2. Ensure you are in grid view not list view
3. Ensure that you have a sound or video file available
4. Select that media file and press play
5. Close the preview modal in the top right

On the current `develop` branch note how the sound from your media file continues to play after the modal is closed.
Switch to this branch and force reload the page in your browser to ensure all javascript files are reloaded too and repeat the above steps, note that this time, closing the modal also stops media file playback.

**Comment by bahiirwa** [comment]
I have manually tested by playing an audio file.

I can concur. I have taken the steps shared by @mattyrob above and the player keeps going in the `develop` branch. But the PR solves the issue.

**Comment by nylen** [comment]
`npm rebuild node-sass` can sometimes fix this issue, otherwise, I'm not sure as I don't have a Mac.

**Review by nylen — APPROVED** [review]
Looks good, thank you both for testing.

**Pull request merged**
