### PR TITLE
Custom issue templates and template chooser

### PR DESCRIPTION
**Pull request by viktorix**
## Description
This PR adds custom issue templates for bug reports, feature requests, and WP backports. Plus, it uses template chooser to allow user to select their issue type or access additional resources as needed.

There are **no core changes**. All changes are in `.github` directory.

## Motivation and context
This helps streamline and standardize issue creation process. It should result in better quality issues, help segment feature requests from bug reports, and possibly eliminate some issues that additional resources might help with (docs, forum, etc.).

Blank issues are disabled to force users to choose between bugs, feature requests, or WP backports. Blank issues can be easily enabled if the need ever arises. 

## How has this been tested?
This can be viewed and tested using the following repo:
https://github.com/viktorix/ClassicPress/issues/new/choose

If you plan to test this in your repo, this must be part of the default branch in GitHub repo settings. This will not work if it's in a regular PR branch.

## Screenshots
image
---
image
---
image
---
image

## Types of changes
- GitHub improvement

### CODE REVIEW

**Review by bahiirwa — COMMENTED** [review]
This works well overall. See https://github.com/viktorix/ClassicPress/issues for sample issues I created. 

However, the type labels do not work as expected. Could these be missing?

**Comment by viktorix** [comment]
@bahiirwa after looking into this, the label must exist prior to issue creation. It didn't exist, so it wasn't used. I just added the labels to my repo, and it works:
https://github.com/viktorix/ClassicPress/issues/5

**Review by bahiirwa — APPROVED** [review]
LGTM as a minor change for making better/guided submissions of issues.

**Review by xxsimoxx — APPROVED** [review]
Very nice!

**Comment by mattyrob** [comment]
Discussed at weekly PR meeting, reviewed already and agreed for merge.

**Comment by joyously** [comment]
I have just encountered the same problem twice. Because of this issue template, GitHub doesn't work correctly.
My normal mode is to find the offending line of code and use GitHub's 3 dot menu on that line to open a new issue referencing that code. But with this template in play, it doesn't work. 
Additionally, none of the choices are valid for opening an issue on the issue template, so it doesn't cover the entire repo.
This makes me less likely to attempt to create an issue, so the project loses out.

**Comment by viktorix** [comment]
@joyously I do see what you mean. I will see if there is a workaround or at least report it to Github as it does look like a bug. 

A quick workaround:
1. When you click on 3 dots, select "Copy permalink".
2. Then click on it again and select "Reference in new issue" - this will open the template chooser.
3.  Select an appropriate template such as Bug. 
4. Paste the permalink in the correct field.

This adds 2 extra clicks to the process, it's not perfect but also not too bad. 

I will also look into adding an additional type for non-code issues.

**Pull request merged**
