### PR TITLE
Update logo image filenames

### LINKED ISSUE #266: Naming schema needed for brand assets (images, logos, etc)
There seems to be a few naming schemas emerging for brand assets, such as logos. I'd like to see a consistent schema decided that will allow for consistency, better predictability, and improved image-search SEO.

## Expected behavior
A consistent, explanatory filename schema for brand assets.

## Current behavior
Brand assets are inconsistently named. For example, in the `./wp-includes/images/` directory, I find the following filenames, which also point out need to standardize capitalization.
* ClassicPress-icon-blue-600.png
* classicpress-logo-dashicon-style.svg

...then, from the [brand assets page](https://docs.classicpress.net/press-and-branding/), there's the following filenames:

* feather-gradient.svg
* feather-white.svg
* icon-gradient-600.png
* icon-gradient.svg
* icon-white.svg
* logo-gradient.svg
* logo-white.svg
 
## Context
The brand assets page has probably the most-aligned filenames (to one another, not the project). However, the filenames have no context outside of that page. If they are named according to a defined schema, we can ensure they always have context, in any context. This may also help with SEO in image searches. The brand assets page should be first result for a search for the CP logo; resolving this issue will help.

## Possible solution
Leave any existing images in place to avoid breaking changes with plugins/themes that may be using them. Introduce newly-named images and use those going forward with a naming schema such as the following:

> brand-purpose-type-color-wxh.ext

```
Coin Logotype
classicpress-logo-coin-green-50x50.svg
classicpress-logo-coin-white-50x50.svg
classicpress-logo-coin-green-50x50.png
classicpress-logo-coin-white-50x50.png

Feather Logotype
classicpress-logo-feather-green-50x50.svg
classicpress-logo-feather-white-50x50.svg
classicpress-logo-feather-green-50x50.png
classicpress-logo-feather-white-50x50.png

Wordmark Logotype
classicpress-logo-wordmark-green-300x50.svg
classicpress-logo-wordmark-white-300x50.svg
classicpress-logo-wordmark-green-300x50.png
classicpress-logo-wordmark-white-300x50.png

Icon/Dashicon/Favicon, et al
classicpress-logo-icon-green-20x20.png
classicpress-logo-dashicon-green-20x20.png
classicpress-logo-favicon-green-20x20.png

```
**Notes**
1. The above size/dimension values were made up.
2. The word 'gradient' is omitted; every colored logo has gradient.
3. Adding a size value to svg images isn't necessary, but consistency is nice.

### PR DESCRIPTION
**Pull request by nylen**
We have various logo image files in our codebase.  This PR cleans them up, adding a standardized naming scheme for the ones we've added in ClassicPress.  Closes #266 for the core code, though we can continue with this task on our [branding assets page](https://docs.classicpress.net/press-and-branding/).

Some filenames and image sizes need to be left as they were in WordPress:

```
src/wp-admin/images/w-logo-blue.png
src/wp-admin/images/w-logo-white.png
src/wp-admin/images/wordpress-logo.png
src/wp-admin/images/wordpress-logo.svg
src/wp-admin/images/wordpress-logo-white.svg
src/wp-includes/images/w-logo-blue.png
```

Where necessary, this PR updates the above files with ClassicPress logos that are sized identically to the corresponding files in WordPress 4.9.  There was also still one instance of the old blue-on-white ClassicPress logo.

---

Other logo image files (the ones added in ClassicPress) have been renamed as follows:

| Before | After |
|--|--|
| `src/wp-includes/images/ClassicPress-icon-blue-600.png` | (removed, not needed) |
| `src/wp-admin/images/cp-logo-gradient.png` | `src/wp-admin/images/classicpress-logo-wordmark-gradient-on-transparent-600x115.png` |
| `src/wp-admin/images/cp-logo-gradient.svg` | `src/wp-admin/images/classicpress-logo-wordmark-gradient-on-transparent.svg` |
| `src/wp-includes/images/classicpress-logo-dashicon-style.svg` | `src/wp-includes/images/classicpress-logo-dashicon-grey-on-transparent.svg` |

### CODE REVIEW

**Comment by nylen** [comment]
Thanks for taking a look @johnalarcon!

**Comment by nylen** [comment]
>src/wp-includes/images/ClassicPress-icon-blue-600.png

Looks like we'll be getting around to updating the filenames on the branding page soon, so just a quick note, the filename for this image should be `classicpress-logo-coin-gradient-on-transparent-600x600.png`. It's the same image that's stored here: [icon-gradient-600.png](https://github.com/ClassicPress/ClassicPress-Network/blob/f7b82970c801291416967c139ae353db189beee6/wp-content/classicpress/logos/icon-gradient-600.png)

**Comment by bahiirwa** [comment]
Is that a typo “coin” for “icon”? 

Side note: do those old files go to list to remove from WP migration?

**Comment by nylen** [comment]
Not a typo, "coin" because it's a circular icon. As opposed to the "feather" image (also an icon) or the "wordmark" logo style.

We haven't removed any WP files related to this issue. The WordPress logo files mentioned in the original post need to be left in place because [existing plugins](https://wpdirectory.net/search/01DNV59BB9EHMRXMNQYZQ1HMFZ) and [themes](https://wpdirectory.net/search/01DNV5AFWHAK4KCTNYC8CAJVW5) reference them, but we have replaced them with a ClassicPress logo of the same size.

**Pull request merged**
