### PR TITLE
A significant start towards coding standards

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
Rebase aganist `develop`
`phpcbf src --standard=/Users/Matthew/Sites/ClassicPress/phpcs.xml.dist`

Then fixes to the following files for unit tests
- src/wp-includes/class-wp-admin-bar.php
- src/wp-admin/includes/widgets.php

## Motivation and context
Improving coding standards should make backports easier, improve code readability and allow us to fully activate automated testing.

## How has this been tested?
Need to ensure unit tests are still passing and manually confirm ClassicPress still functions as normal

## Screenshots
N/A

## Types of changes
- Coding Standards

### CODE REVIEW

**Comment by mattyrob** [comment]
Running the following on the command line:
`phpcs src --report=summary --standard=/Users/Matthew/Sites/ClassicPress/phpcs.xml.dist`

On `develop` I am getting a summary report of:

**A TOTAL OF 51169 ERRORS AND 16094 WARNINGS WERE FOUND IN 513 FILES**

On this PR I am getting:

**A TOTAL OF 1555 ERRORS AND 5176 WARNINGS WERE FOUND IN 347 FILES**

**Comment by KTS915** [comment]
That's pretty impressive progress!

**Comment by bahiirwa** [comment]
@mattyrob Can be rebase this branch before the PR comes in, It i was way behind and making the review a bit gigantic.

**Comment by mattyrob** [comment]
@nylen - Any advise on how the rebase can be implemented to make reviewing this PR easier?

I was investigating but have throughly confused myself now!

**Comment by mattyrob** [comment]
@bahiirwa - Thanks for your patience, I've managed to figure out how to clean this PR up and have pushed an updated version with 2 commits, the first is all of the automated fixes and the second is a fix for some unit tests that now fail due to the white space changes in core.

**Review by bahiirwa — COMMENTED** [review]
I am still reviewing but a these are something we can discuss.

1. Some `includes()` are changed to `require()` this might have consequences or not. 

2. Some of the code after `<?php` is indented with a tab and others do not. They are all vertically aligned. I might need this rule in the docs but do we want to have a general behavior? Ref: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#opening-and-closing-php-tags

**Comment by mattyrob** [comment]
Having looked at the examples above I think the change from `include` to `require` is generally correct. The file that is loaded is 'required' for the page to function correctly, if the file is not present for some reason then PHP will ERROR on the `require` statement and stop. If we keep with `include` then PHP will issue a warning and continue, likely resulting in unusual behaviour.

As for the `<?php` indentation, can you give an example for review?

**Comment by mattyrob** [comment]
@bahiirwa - I've had another look at this as I'm going to press forwards with the coding standards.

In terms of the `<?php` tags I presume you means code indention like this:

```
<?php if ( get_locale() !== 'en_US' ) { ?>
	<p class="about-inline-notice notice-warning">
		<?php
		printf(
			/* translators: link to learn more about translating ClassicPress */
			__( 'Help us translate ClassicPress into your language! <a href="%s">Learn more</a>.' ),
			'https://www.classicpress.net/translating-classicpress/'
		);
		?>
	</p>
<?php } ?>
```

It may look inconsistent at first glance but I think it is correct. The first `<?php` is an inline example with the opening and closing tags on the same line. It therefore makes sense that the next line of HTML is indented and the same applied to the opening `<?php` on te next line. Then the PHP code is initially indented to the same level until the PHP styling comes into play. And closing tags for multiline code is indented to the same level.

As far as I can tell this is one for the PHPCS 'Generic' sniffs so it is broadly accepted well beyond WP.

I'm going to leave this here for a few days and then commit if there is not further comment, these changes are all from well tested, automated whitespace corrections and merging this to `develop` should help massively with backports.

**Comment by bahiirwa** [comment]
@mattyrob Carry on

**Pull request merged**
