### PR TITLE
Restore Comment_Walker::comment function

### LINKED ISSUE #1645: 🐞 Comment Function Removed from Walker_Comment
### Expected behavior

My code expects the comment function inside Walker_Comment and it no longer exists.

### Current behavior

Since comment is removed, assume because HTML5 is default, only html5_comment exists. 

### Possible solution

Would suggest, for backcompat, that the comment function be restored, but simply call the html5_comment function. 

### Steps to reproduce bug

Try to call Walker_Comment::comment

### Context

_No response_

### ClassicPress version

2.2.0

### PHP version

I don't know

### Can you help?

I can help test a solution

### PR DESCRIPTION
**Pull request by mattyrob**
## Description
This PR fixes #1645 
It reintrodyced the `comment` function to the `Comment_Walker` class as a wrapper for the `html5_comment` function.

## Motivation and context
Backwards compatibility
Fixes #1645

## How has this been tested?
Includes a new unit test
OP offered to test also so that would be very useful.

## Screenshots
N/A

## Types of changes
- Bug fix

### CODE REVIEW

**Comment by pattonwebz** [comment]
The test here added seems a little unusual to me. The double calling to ensure you have both odd and even in both instances so they are the same is mostly what jumps out as odd. It tests a behaviour that isn't relevant to the unit.

The unit cares only to check that the comment method exists. You could simply call it through the wrapper and check that it does not throw an error?

**Comment by mattyrob** [comment]
@pattonwebz - the original `Comment_Walker::comment()` function in core is protected so accessing it is a challenge.

The test contains a wrapper class that exposes the parent `comment()` and html5_comment()` functions.

I'm not only testing that the function exists but also that the output is the same

I was finding in my tests that If i called each function with one comment they were rendered sequentially, so one had a class od `odd` and the other `even` to the output could not be compared.

I suppose another way is to created 2 comment on the post and compare the output with 2 different comments.

**Comment by pattonwebz** [comment]
@mattyrob I get why you have the double call and I know why it solves the issue with comparing them. There is a comment that explains it so even if I find it strange it's easy to see why it is the way it is.

What the current test looks like seems like a supplementary test that checks behaviour but it isn't a minimal test to verify what you fixed here was my point.

A minimal test would just confirm that things no longer error due to method not existing if something calls the function you restored. I would write a test that asserts this.

I don't think you should remove the test you already wrote because it tests expectations for how the functions behave - but it doesn't explicitly check what you have fixed (it only checks it implicitly).

**Review by xxsimoxx — APPROVED** [review]
LGTM

**Pull request merged**
