### PR TITLE
Fixed typo donation link in README.md file

### PR DESCRIPTION
**Pull request by Remzi1993**
Fixed typo donation link in README.md file

### CODE REVIEW

**Comment by bahiirwa** [comment]
Looks good.

**Comment by Remzi1993** [comment]
@bahiirwa Could you (force) merge this? The develop branch fails Travis CI: PHP: 7.1
with environment variable: WP_TRAVISCI=travis:precommit-and-js

This has nothing to do with my PR, because I only changed one line in the README.md file.

**Comment by nylen** [comment]
Thanks for the PR @Remzi1993!

Let's fix the build first... it looks related to #416 and I should be able to do this later today.

**Comment by Remzi1993** [comment]
@nylen You're welcome 👍  I'm not a git expert, but I think it's safe to merge this and fix the Travis issue later. I don't know what kind of feature is introduced in #416

**Comment by Mte90** [comment]
The travis issue si not related to this pr but something about twemoji, I will look in that

**Comment by nylen** [comment]
>I think it's safe to merge this and fix the Travis issue later

It is a good rule not to merge anything if the build is failing, no matter what the reason is. This way we never end up with a "build: failing" badge in our main readme, and when build issues do occur we are not allowed to be lazy and avoid fixing them.

#446 will fix this issue, so that PR and this one will be merged tonight.

**Pull request merged**
