### PR TITLE
WP-r53897: Database: Ignore display width for integer data types in dbDelta() on MySQL 8.0.17 or later.

### PR DESCRIPTION
**Pull request by bahiirwa**
MySQL 8.0.17 deprecated the display width attribute for integer data types:

    As of MySQL 8.0.17, the ZEROFILL attribute is deprecated for numeric data types, as is the display width attribute for integer data types. You should expect support for ZEROFILL and display widths for integer data types to be removed in a future version of MySQL. Consider using an alternative means of producing the effect of these attributes. For example, applications can use the LPAD() function to zero-pad numbers up to the desired width, or they can store the formatted numbers in CHAR columns.

In practice, this means that display width is removed for integer types when creating a table:

    BIGINT(20) → BIGINT
    INT(11) → INT
    MEDIUMINT(9) → MEDIUMINT
    SMALLINT(6) → SMALLINT
    TINYINT(4) → TINYINT 

Note: This only applies specifically to MySQL 8.0.17 or later. In MariaDB, display width for integer types is still available and expected.

This commit ensures that dbDelta(), which relies on the DESCRIBE SQL command to get the existing table structure and field types, when running on MySQL 8.0.17 or later, does not unnecessarily attempt to convert BIGINT fields back to BIGINT(20), INT back to INT(11), etc. When comparing the field type in the query with the existing field type, if display width is the only difference, it can be safely ignored to match MySQL behavior.

The change is covered by existing dbDelta() unit tests:

    A test for not altering wp_get_db_schema() queries on an existing install using MySQL 8.0.17+ now passes.
    More than twenty tests which previously failed on PHP 8.0.x + MariaDB due to incorrect expectations, caused by MariaDB version reporting not being consistent between PHP versions, now pass. 

References:

    [MySQL: Nymeric Type Attributes](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html)
    [MariaDB: Numeric Data Types](https://mariadb.com/kb/en/data-types-numeric-data-types/) 

Follow-up to [[1575]](https://core.trac.wordpress.org/changeset/1575), [[18899]](https://core.trac.wordpress.org/changeset/18899), [[37525]](https://core.trac.wordpress.org/changeset/37525), [[47183]](https://core.trac.wordpress.org/changeset/47183), [[47184]](https://core.trac.wordpress.org/changeset/47184).

Props SergeyBiryukov, pbearne, leewillis77, JavierCasares, desrosj, costdev, johnbillion.
Fixes [#49364](https://core.trac.wordpress.org/ticket/49364). See [#51740](https://core.trac.wordpress.org/ticket/51740).

### CODE REVIEW

**Comment by bahiirwa** [comment]
I had to introduce [Changeset 47451](https://core.trac.wordpress.org/changeset/47451) which allows the tests to pass. 

It Introduces wpdb::db_server_info() to retrieve full MySQL server information string as supplied by mysqli_get_server_info().

This complements wpdb::db_version(), which only returns a numeric version string and strips any additional information, e.g. vendor name.

**Comment by mattyrob** [comment]
I've managed to re-create this PR locally, backporting in order and have it passing tests locally, @bahiirwa - are you happy if I create a new PR and close this one - might be quicker than trying to find the issue code.

**Comment by bahiirwa** [comment]
Please @mattyrob

**Comment by mattyrob** [comment]
PR was re-created and erroneosuly pushed to `develop`, tests all pass, see commits:

https://github.com/ClassicPress/ClassicPress/commit/eb449e97a40b0f7327408202b43a764d39b53178
https://github.com/ClassicPress/ClassicPress/commit/b82dcaec7f44f24de3195762e51fade54df4c723
https://github.com/ClassicPress/ClassicPress/commit/445373e1434c37af635e189fc288e27dafa793a1

**Pull request closed without merging**
