### PR TITLE
XMLRPC - Editing a draft post with wp.editPost causes its published date to be set

### PR DESCRIPTION
**Pull request by bahiirwa**
## Description
Dates being set wrong in posts to WordPress. The issue in summary is that if you have a draft post on WordPress, changing its status to “Published” doesn’t update the publish date from the time the draft was originally saved.

The post has a published date corresponding to the time I first starting writing the post, and when we finally go to publish the podcast, the date remains the same.

## Motivation and context
https://core.trac.wordpress.org/ticket/45322

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by nylen** [comment]
Thanks for the PR @bahiirwa.

Is this a problem you're experiencing on a live site? What software are you using that communicates with the site using XML-RPC?

**Comment by bahiirwa** [comment]
Thanks for the review. This was a backport from the core trac issue.

This is not a personal problem to me but there are reports. For context please read this.

> For a long time, I heard reports from my customers that dates were being set wrong in posts to WordPress. The issue in summary is that if you have a draft post on WordPress, changing its status to “Published” doesn’t update the publish date from the time the draft was originally saved.

> I didn’t really get a handle on this problem until it started affecting me. Sometimes I write the show notes for my podcast, Core Intuition, ahead of the time the podcast actually goes public. In these situations, the blog post has a published date corresponding to the time I first starting writing the post, and when we finally go to publish the podcast, the date remains the same.

Cite: https://bitsplitting.org/2019/05/24/unloved-patches/

Software it applies: https://red-sweater.com/marsedit/

**Comment by nylen** [comment]
OK, got it.

Generally when evaluating bugfix PRs I look for these things (ideally all of them)

- The change impacts existing ClassicPress users. (Otherwise, there are literally thousands of things we could look at, but we need to prioritize our development time.)
- The change is not going to break any other use cases.
- The change has automated tests.
- I understand the change very well, or I can ask questions of someone who understands it very well.

I think this PR meets all criteria except the first one.  I understand this part of the code better than I'd like, because I wrote the workarounds for this issue in the WP REST API.

We also discussed it a bit in Slack and decided to accept this one: https://classicpress.slack.com/archives/CCCF22HG8/p1560534419056600

**Comment by bahiirwa** [comment]
> Generally when evaluating bugfix PRs I look for these things (ideally all of them)
> 
> * The change impacts existing ClassicPress users. (Otherwise, there are literally thousands of things we could look at, but we need to prioritize our development time.)
> * The change is not going to break any other use cases.
> * The change has automated tests.
> * I understand the change very well, or I can ask questions of someone who understands it very well.
> 


Could we adopt this in the contributions section of the read me? It might iron out some issues for PRs

**Comment by nylen** [comment]
Copy/pasting from https://www.classicpress.net/blog/development-update-august-2019/ because we are linking to this PR from our `1.1.0` changelog:

>Previously, when writing a blog post using the XML-RPC API, if you saved the post as a draft, then came back and published it at a later date, the post published with the original draft date, rather than the publish date. We have changed this behavior and now blog post dates correspond to the actual publish date. Our thanks to Daniel Jalkut, who [wrote about this issue](https://bitsplitting.org/2019/05/24/unloved-patches/) and [wrote the patches for WordPress](https://core.trac.wordpress.org/ticket/45322) that we accepted in this release, and to Laurence Bahiirwa for proposing the patch for ClassicPress.
>
>Note that this issue **does not** apply to **normal** edits from within the ClassicPress dashboard, only when using the XML-RPC API, which is usually seen when writing posts with external editors.

**Pull request merged**
