### PR TITLE
Enlarge draggable area in dashboard and post metaboxes

### PR DESCRIPTION
**Pull request by KTS915**
This PR is a response to https://forums.classicpress.net/t/cp2-0-cannot-drag-and-drop-boxes-on-dashboard/5112

## Description
When modernizing the dashboard and post metaboxes for CP v2, the draggable area of the metabox title bar was reduced in width. This PR restores the draggable area to its former width while taking account of the fact that the metabox now uses a disclosure widget.

There's also a little bit of file tidying to remove comment references to jQuery UI.

## How has this been tested?
Tested on my localhost and also at https://forums.classicpress.net/t/cp2-0-cannot-drag-and-drop-boxes-on-dashboard/5112/23

### CODE REVIEW

**Review by xxsimoxx — APPROVED** [review]
LGTM

**Comment by mattyrob** [comment]
This may need some more work, in Safari the title of the box is vertically enlarged and the toggle arrow to expand and collapse the meta box is located away from the title text.

Screenshot 2024-03-09 at 08 43 44

**Comment by KTS915** [comment]
Oh, Safari!! Latest commit addresses this by reducing the width of the `div` involved by 1% in each case.

**Review by mattyrob — APPROVED** [review]

**Comment by mattyrob** [comment]
Most recent change has fixed the view in Safari.

**Pull request merged**
